package org.meristem.oneapp.usersservice.integrations.requests;

import lombok.Builder;

@Builder
public record CreateMinorCustomerRequest(
        String titleCd,
        String lastName,
        String firstName,
        String otherNames,
        String genderCd,
        String birthDate,
        String motherMaidenName,
        String parentCustomerId,
        String nationalityCd,
        String mobilePhoneNo,
        String alternatePhoneNo,
        String primaryEmailAddress,
        String alternateEmailAddress,
        String addressStreet,
        String addressCity,
        String addressStateCd,
        String addressCountryCd,
        String addressZipCode,
        String bankCd,
        String bankAccountName,
        String bankAccountNo,
        String bankBranchName,
        String bankAddressDetails,
        String identityDocTypeCd,
        String identityDocName,
        String identityDocNo,
        String identityDocIssueDate,
        String identityDocExpiryDate,
        String identityDocIssueAuthority,
        String locationCd,
        String externalReference1,
        String externalReference2,
        String externalCrmId,
        String officerId,
        String introducerId,
        String parentFirstName,
        String parentLastName,
        String parentTitleCd,
        String parentGenderCd,
        String parentMobilePhoneNo,
        String parentEmailAddress,
        String parentAddressStreet,
        String parentAddressCity,
        String parentAddressStateCd,
        String parentAddressCountryCd,
        String parentIdentityDocTypeCd,
        String parentIdentityDocNo,
        String parentRelationshipCd
) {
}
