{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    kubernetes.io/elb.id: {{ .Values.ingress.elbId }} # Replace it with the ID of your existing load balancer.
    kubernetes.io/elb.ip: {{ .Values.ingress.elbIp }}  # Replace it with the IP of your existing load balancer.
    kubernetes.io/elb.class: performance # Load balancer type
    kubernetes.io/elb.port: "443"
    kubernetes.io/ingress.class: "cce"
    kubernetes.io/elb.tls-certificate-ids: {{ .Values.ingress.certificateIds }} #ELB certificate IDs, which are separated by comma (,) To obtain the certificate, log in to the CCE console, choose Service List > Networking > Elastic Load Balance, and click Certificates in the navigation pane. In the load balancer list, copy the ID under the target certificate name.
    kubernetes.io/elb.tls-ciphers-policy: "tls-1-2-fs" #"tls-1-2-fs"
    kubernetes.io/elb.http2-enable: "true"
    kubernetes.io/elb.pool-protocol: "https"
    kubernetes.io/elb.gzip-enabled: "true" #data compression, which reduces the size of files to be transferred, improves file transfer efficiency, and reduces the bandwidth needed for the transmission.
    #kubernetes.io/elb.listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    #kubernetes.io/elb.ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  ingressClassName: cce # Specify the ingress class name. The default value is cce.
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix # or ImplementationSpecific
            backend:
              service:
                name: {{ include "middleware-service.fullname" . }}
                port:
                  number: {{ .Values.ingress.servicePort }}
{{- end }}
