{{/*
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Values.pvc.name }}
#   namespace: {{ .Values.global.namespace | default .Release.Namespace }}
# spec:
#   accessModes: {{ toYaml .Values.pvc.accessModes | nindent 4 }}
#   resources:
#     requests:
#       storage: {{ .Values.pvc.resources.requests.storage }}
#   storageClassName: {{ .Values.pvc.storageClassName }}
#   volumeMode: {{ .Values.pvc.volumeMode | default "Filesystem" }}
*/}}