# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount-middleware.name }}
  namespace: {{ .Values.global.middleware-namespace }}
  annotations:
    cce.io/dew-resource: {{ .Values.serviceAccount.dewResources | toJson | quote }}

---
# Role - only if you want to allow reading secrets via Kubernetes API

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "middleware-service.fullname" . }}-role
  namespace: {{ .Values.global.middleware-namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "middleware-service.fullname" . }}-rolebinding
  namespace: {{ .Values.global.middleware-namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "middleware-service.fullname" . }}-sa
    namespace: {{ .Values.global.middleware-namespace }}
roleRef:
  kind: Role
  name: {{ include "middleware-service.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
