apiVersion: v1
kind: Service
metadata:
  name: {{ include "middleware-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "middleware-service.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    app: {{ include "middleware-service.name" . }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}