spring:
  application:
    name: notification-service

  config:
    import: configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      profile: local
      label: dev
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}


  termii:
    baseUrl: https://v3.api.termii.com
    apiKey: TLXeXGvxErNgYvvqZxOCQYvbIGCTTiJctbjWxhODZlCtlSauFQrJpzCeGjLRlh
    apiSecret: tsk_okU2kft3QCk7tJC2jMxi16oZUN
