services:
  # ======================
  # REDIS SERVICE (Internal only)
  # ======================
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    command: redis-server --requirepass 'AHjsoie67&8*'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=AHjsoie67&8*
    volumes:
      - redis_data:/data
    networks:
      - meristem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  # ======================
  # KAFKA SERVICE (Internal only)
  # ======================
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
    volumes:
      - kafka_data:/var/lib/kafka/data
      - kafka_secret:/etc/kafka/secrets
    networks:
      - meristem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 30s
      retries: 2  # Kafka can take 2-3 minutes to start

  # ======================
  # CONFIG SERVER (Internal only)
  # ======================
  config-server:
    image: config-server
    container_name: config-server
    networks:
      - meristem-network
    depends_on:
      - redis
      - kafka
      - postgres
    environment:
      - COMPANY_NAME="Meristem Securities Limited"
      - DATA_PRIVACY_POLICY_URL=https://www.onemerristem.merristem.com
      - GREEN_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Green%20Logo.png
      - WHITE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20White%20Logo.png
      - FINANCE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Finance%20%28Green%29.png
      - SPRING_PROFILES_ACTIVE=default
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GITHUB_URL=${GITHUB_URL}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START=true
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_TIMEOUT=30  # Default is 5s (often too short)
      - SPRING_CLOUD_CONFIG_SERVER_GIT_REFRESH_RATE=10  # Check for updates every 10s
      - H2_PASSWORD=${H2_PASSWORD} 
    restart: unless-stopped

  # --------------------
  # CONSUL
  # ---------------------
  consul:
    container_name: consul
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    networks:
      - meristem-network
    ports:
      - "8500:8500"
    restart: unless-stopped
    image: consul:1.15.4

  # ======================
  # POSTGRESQL DATABASE (Internal only)
  # ======================
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
        #- POSTGRES_MULTIPLE_DATABASES=${DB_NAME_USER_SERVICES},${DB_NAME_NOTIFICATION_SERVICES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # The Database init-db.sh to be run in order to create the databases
    networks:
      - meristem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]

  # ======================
  # USERS SERVICE (Internal only)
  # ======================
  users-service:
    image: users-service
    container_name: users-service
    networks:
      - meristem-network
    depends_on:
      - config-server
      - postgres
      - redis
      - kafka
      - consul
    environment:
      - COMPANY_NAME="Meristem Securities Limited"
      - DATA_PRIVACY_POLICY_URL=https://www.onemerristem.merristem.com
      - GREEN_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Green%20Logo.png
      - WHITE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20White%20Logo.png
      - FINANCE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Finance%20%28Green%29.png
        #- SPRING_PROFILES_ACTIVE=default
      - SMILE_ID_PARTNER_ID=7496
      - SMILE_ID_PROD_API_KEY=ugXtYHgdgqYtNEkMGnKBkhTUeN4ZKx7dhN4D5rn1vAIVUh1uVmJpW1heUy6MvXOKpUxIcnVBnaVU7bZ4PrGdocNcFmuf2m9ZRQeLW2wGQosotIfZEyRLdq9wgYFlgkBeszKoG98wPGvrNLAXP9Txehvid202jfaQtH5KCz5x0FI=
      - SMILE_ID_DEV_API_KEY=3d64d61d-6d64-402d-a5f0-fa288507ec8f
      - SMILE_ID_PROD_LAMBDA_URL=https://api.smileidentity.com/v1/
      - SMILE_ID_TEST_LAMBDA_URL=https://testapi.smileidentity.com/v1/
      - SMILE_ID_PROD_WHITELIST_IPS=34.240.137.52,44.230.128.108,52.36.32.43,52.213.46.74
      - SMILE_ID_DEV_WHITELIST_IPS=35.166.227.53,44.246.19.66,54.246.37.255,99.81.237.141
      - SMILE_ID_DEV_CALLBACK_URL=https://www.onemerristem.merristem.com/api/users/onboard/smile-id/webhook
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GITHUB_PROFILE=local
      - GITHUB_BRANCH=wallet
      - USER="System"
      - ONE_APP_SERVER_URL=http://110.238.74.43:8080
      - ONE_APP_EMAIL=hello@onemeristem.meristemng.com
      - DB_SERVER=jdbc:postgresql://postgres:5432 # input the private ip here
      - USERS_DB_NAME=${DB_NAME_USERS_SERVICE}
      - USERS_DB_USERNAME=${DB_USERS_USERNAME}
      - USERS_DB_PASSWORD=${DB_USERS_PASSWORD}
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_HOST_URL=${KAFKA_HOST}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_USERNAME=${MAILER_USERNAME}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - CONSUL_HOST=consul
      - HUAWEI_ACCESS_KEY_ID=HPUAM5DHA70WCCJGFNK7
      - HUAWEI_SECRET_ACCESS_KEY_ID=rpI0upf6nnHNnLze4DLkXXofufV70EuqwfJIIukx
      - HUAWEI_OBS_ENDPOINT='obs.af-south-1.myhuaweicloud.com'
      - HUAWEI_OBS_IMAGES_BUCKET='obs-image-storage-one-meristem-dev-env'
      - HUAWEI_OBS_DOC_BUCKET='obs-documents-one-meristem-dev-env'
      - OKHI_DEV_AND_PROD_WHITELIST_IP=52.18.220.93,18.202.96.242
     # - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  # ======================
  # NOTIFICATION SERVICE (Internal only)
  # ======================
  notification-service:
    image: notification-service
    container_name: notification-service
    networks:
      - meristem-network
    depends_on:
      - config-server
      - postgres
      - kafka
      - redis
      - consul
    environment:
      - COMPANY_NAME="Meristem Securities Limited"
      - DATA_PRIVACY_POLICY_URL=https://www.onemerristem.merristem.com
      - GREEN_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Green%20Logo.png
      - WHITE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20White%20Logo.png
      - FINANCE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Finance%20%28Green%29.png
      - SPRING_PROFILES_ACTIVE=default
      - GITHUB_BRANCH=wallet
      - GITHUB_PROFILE=local
      - ONE_APP_SERVER_URL=http://110.238.74.43:8080
      - ONE_APP_EMAIL=hello@onemeristem.meristemng.com
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DB_SERVER=jdbc:postgresql://postgres:5432 # input the private ip here
      - NOTIFICATION_DB_NAME=${DB_NAME_NOTIFICATION_SERVICE}
      - NOTIFICATION_DB_PASSWORD=${DB_NOTIFICATION_PASSWORD}
      - NOTIFICATION_DB_USERNAME=${DB_NOTIFICATION_USERNAME}
        #- WALLET_DB_NAME=${DB_NAME_WALLET_SERVICE}
        #- WALLET_DB_PASSWORD=${DB_WALLET_PASSWORD}
        #- WALLET_DB_USERNAME=${DB_WALLET_USERNAME}
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI}
      - KAFKA_HOST_URL=${KAFKA_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_USERNAME=${MAILER_USERNAME}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - CREDIT_SWITCH_LOGIN_ID=315497
      - CREDIT_SWITCH_PUBLIC_KEY=1kepf1KlXc9EUjPSMcqBvQf5EIqLWnXuEEz58XbiMyfLQEDfOpDltmMRHG88M3tmcSARuW9G6iMc9ExYMjfJwfI3MI
      - CREDIT_SWITCH_PRIVATE_KEY=UNlYfANQ5hfpEjuaSIFjXOSK97NAX6NI0pT2ACpa5aPIi04Lc3swpj8XzscxJZPrzjUb1Yd1EFM5Z5yp8Tx5HwaIs9
      - CREDIT_SWITCH_SMS_MERCHANT_NAME='Meristem Securities Limited'
      - CREDIT_SWITCH_SMS_PASSWORD='@wMJ=otlD3(b'
      - CREDIT_SWITCH_SMS_BASEURL='http://176.58.99.160:9014/api/v1/'
      - CREDIT_SWITCH_SMS_SENDER_ID=Meristem
    restart: unless-stopped

  # ======================
  # API GATEWAY (Exposed publicly)
  # ======================
  cloud-gateway:
    image: cloud-gateway
    container_name: cloud-gateway
    ports:
      - "8080:20010"  # Exposed for HTTP
      - "443:20010" # Exposed for HTTPS
    networks:
      - meristem-network
    depends_on:
      - config-server
      - users-service
      - notification-service
      - redis
      - postgres
      - kafka
      - consul
    environment:
      - COMPANY_NAME="Meristem Securities Limited"
      - DATA_PRIVACY_POLICY_URL=https://www.onemerristem.merristem.com
      - GREEN_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Green%20Logo.png
      - WHITE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20White%20Logo.png
      - FINANCE_LOGO_URL=https://obs-unstructured-data-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/logos/Meristem%20Finance%20%28Green%29.png
      - SPRING_PROFILES_ACTIVE=default
      - GITHUB_BRANCH=wallet
      - GITHUB_PROFILE=local
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SERVER_PORT=20010 #Reinforce the port setting
        #- MANAGEMENT_SERVER=-1 #Disable the actuator port
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI}
      - USER_SERVICE_URI=${USER_SERVICE_URI}
      - NOTIFICATION_SERVICE_URI=${NOTIFICATION_SERVICE_URI}
      - WALLET_SERVICE_URI=${WALLET_SERVICE_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SSL_KEY_ALIAS=one-meristem-app
      - KEY_STORE_PASSWORD=oneApp231
        #- SSL_CERT_PATH=/etc/ssl/certs/certificate.pem
        #- SSL_CERT_PASSWORD=${CERT_PASSWORD}  
        #- SERVER_ADDRESS=${VM_PUBLIC_IP}   # Add this line with your public IP, Use your public endpoint here for the HTTP
     # - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]

# ======================
# INFRASTRUCTURE
# ======================
networks:
  meristem-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  kafka_secret:
  consul:


