version: '3'
services:
  # Cloud Gateway Service
  cloud-gateway:
    build:
      context:./backend/cloud-gateway
      dockerfile: Dockerfile-cloud-gateway
    ports:
      - "20010:20010"
    depends_on:
      - config-server
      - users-service
      - notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/one_meristem_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  # Config Server
  config-server:
    build:
      context:./backend/config-server
      dockerfile: Dockerfile-config-server
    ports:
      - "20000:20000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/one_meristem_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  # Users Service
  users-service:
    build:
      context:./backend/users-service
      dockerfile: Dockerfile-users-service
    ports:
      - "20020:20020"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/one_meristem_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  # Notification Service
  notification-service:
    build:
      context:./backend/notification-service
      dockerfile: Dockerfile-notification-service
    ports:
      - "20030:20030"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/one_meristem_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  # Mobile App
  mobile-app:
    build:
      context:./mobile-app
      dockerfile: Dockerfile-mobile-app
    ports:
      - "8081:8081"
    depends_on:
      - cloud-gateway
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEVTOOLS_PORT=19002
