#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create Main Database
    CREATE DATABASE ${DB_NAME_USER_SERVICES};
    
    -- Create Notification Database
    CREATE DATABASE ${DB_NAME_NOTIFICATION_SERVICES};
    
    -- Grant All Privileges to the Postgres User
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME_USER_SERVICES} TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME_NOTIFICATION_SERVICES} TO ${POSTGRES_USER};
    
    -- Create Extensions (if needed)
    \c ${DB_NAME_USER_SERVICES}
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    
    \c ${DB_NAME_NOTIFICATION_SERVICES}
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";

    -- Revoke Public Access
    REVOKE CONNECT ON DATABASE ${DB_NAME_USER_SERVICES} FROM PUBLIC;
    REVOKE CONNECT ON DATABASE ${DB_NAME_NOTIFICATION_SERVICES} FROM PUBLIC;
EOSQL
