spring:
  application:
    name: users-service
  config:
    import: configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      label: dev
      profile: local
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}


# TODO: DELETE
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
spring.datasource.hikari.data-source-properties.logUnclosedConnections: true
logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
logging.level.com.zaxxer.hikari: TRACE
