CREATE TABLE user_expo_tokens
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    user_id            BIGINT,
    device_id          VARCHAR(300)                            NOT NULL,
    expo_token         VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_user_expo_tokens PRIMARY KEY (id),
    CONSTRAINT uk_user_expo_tokens_token UNIQUE (expo_token)
);

CREATE INDEX idx_user_expo_tokens_user_id ON user_expo_tokens (user_id);
CREATE INDEX idx_user_expo_tokens_token ON user_expo_tokens (expo_token);


CREATE TABLE expo_notification_ticket
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    ticket_id          VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_expo_notification_ticket PRIMARY KEY (id),
    CONSTRAINT uk_pk_expo_notification_ticket_ticket_id UNIQUE (ticket_id)
);

CREATE INDEX idx_expo_notification_ticket_ticket_id ON expo_notification_ticket (ticket_id);


CREATE TABLE one_signal_subscriptions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER                                          DEFAULT 0,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    user_id            BIGINT,
    device_id          VARCHAR(300)                            NOT NULL,
    subscription_id    VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_one_signal_subscriptions PRIMARY KEY (id),
    CONSTRAINT uk_one_signal_subscriptions_token UNIQUE (subscription_id)
);

CREATE INDEX idx_one_signal_subscriptions_user_id ON one_signal_subscriptions (user_id);
