-- Users table, populated once a user signs up
CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    email              VARCHAR(200)                            NOT NULL,
    first_name         VARCHAR(150)                            NOT NULL,
    last_name          VARCHAR(150)                            NOT NULL,
    middle_name        VARCHAR(150),
    password           VARCHAR(200)                            NOT NULL,
    phone_number       VARCHAR(50)                             NOT NULL,
    referral_code      VARCHAR(100),
    onboarding_completed BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    users_id          BIGINT NOT NULL,
    roles_id          BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (id)
);

CREATE TABLE permissions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE roles_permissions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    roles_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL,
    CONSTRAINT pk_roles_permissions PRIMARY KEY (id)
);

-- Populated when a user signs up
CREATE TABLE user_profile
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    user_id            BIGINT                                  NOT NULL,
    picture_url        VARCHAR(500),
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);


-- This should be prepopulated with initial values
-- Contains the different features
CREATE TABLE feature_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    name               VARCHAR(100)                            NOT NULL,
    code               VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_feature_type PRIMARY KEY (id)
);

-- This should be prepopulated with initial values
-- Contains the different requirements for each services
CREATE TABLE requirements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    requirement_type   SMALLINT                                 NOT NULL,
    feature_type_id    BIGINT                                  NOT NULL,
    requirement_stage  SMALLINT                                 NOT NULL,
    required           BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_requirements PRIMARY KEY (id)
);

DO $$
DECLARE
    f_id1 integer;
    f_id2 integer;
    f_id3 integer;
BEGIN
INSERT INTO feature_type (
    created_date, created_by, last_modified_date, last_modified_by, version,
    name, code
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 'STOCK', 'ONE_APP_STOCK') RETURNING id  INTO f_id1;

INSERT INTO feature_type (
    created_date, created_by, last_modified_date, last_modified_by, version,
    name, code
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 'TREASURY_BILLS', 'ONE_APP_TREASURY_BILLS') RETURNING id  INTO f_id2;

INSERT INTO feature_type (
    created_date, created_by, last_modified_date, last_modified_by, version,
    name, code
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 'MUTUAL_FUNDS', 'ONE_APP_MUTUAL_FUNDS') RETURNING id  INTO f_id3;

INSERT INTO requirements (
    created_date, created_by, last_modified_date, last_modified_by, version,
    requirement_type, feature_type_id, requirement_stage, required
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 3, f_id1, 1, TRUE);

INSERT INTO requirements (
    created_date, created_by, last_modified_date, last_modified_by, version,
    requirement_type, feature_type_id, requirement_stage, required
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 3, f_id2, 1, TRUE);

INSERT INTO requirements (
    created_date, created_by, last_modified_date, last_modified_by, version,
    requirement_type, feature_type_id, requirement_stage, required
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 3, f_id3, 1, TRUE);
END $$;


-- Populated when the user uploads a document for a particular requirement
CREATE TABLE user_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    name               VARCHAR(255)                            NOT NULL,
    url                VARCHAR(1000)                           NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_document PRIMARY KEY (id)
);

-- Populated when a user enrols for a particular feature
CREATE TABLE user_feature
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    user_id            BIGINT                                  NOT NULL,
    feature_type_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_feature PRIMARY KEY (id)
);

-- Stores the onboarding flow of the user
CREATE TABLE user_onboarding
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    user_id            BIGINT                                  NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    completed          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_onboarding PRIMARY KEY (id)
);

-- OTP verification table, stores the otp and marks it as verified once they verify it,
-- a user_id can have more than one otp row
CREATE TABLE otp_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    code               INT                                     NOT NULL,
    user_id            VARCHAR(200)                            NOT NULL,
    otp_type           INTEGER                                 NOT NULL,
    verified           BOOLEAN DEFAULT FALSE                   NOT NULL,
    expires_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_otpverification PRIMARY KEY (id)
);

ALTER TABLE otp_verification
    ADD CONSTRAINT uc_otpverification_code UNIQUE (code, user_id, otp_type);

CREATE INDEX idx_otpverification_code_user_otp ON otp_verification (code, user_id, otp_type);
CREATE INDEX idx_otpverification_user_otp ON otp_verification (user_id, otp_type);

ALTER TABLE feature_type
    ADD CONSTRAINT uc_feature_type_code UNIQUE (code);

ALTER TABLE feature_type
    ADD CONSTRAINT uc_feature_type_name UNIQUE (name);

ALTER TABLE requirements
    ADD CONSTRAINT uc_requirement_and_user_type UNIQUE (requirement_type, feature_type_id);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_user UNIQUE (user_id);

ALTER TABLE user_document
    ADD CONSTRAINT uc_user_requirement_document UNIQUE (requirement_id, user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

CREATE INDEX idx_users_email ON users (email);

ALTER TABLE requirements
    ADD CONSTRAINT FK_REQUIREMENTS_ON_FEATURE_TYPE FOREIGN KEY (feature_type_id) REFERENCES feature_type (id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_feature
    ADD CONSTRAINT FK_USER_FEATURE_ON_FEATURETYPE FOREIGN KEY (feature_type_id) REFERENCES feature_type (id);

ALTER TABLE user_feature
    ADD CONSTRAINT FK_USER_FEATURE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_usersroles_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_usersroles_on_users FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permissions_id) REFERENCES permissions (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);
