CREATE TABLE transactions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(255)                            NOT NULL,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by       VARCHAR(255)                            NOT NULL,
    version                INTEGER                                          DEFAULT 0 NOT NULL,
    status                 INTEGER                                          DEFAULT 1 NOT NULL,

    transaction_status     INTEGER                                 NOT NULL,
    entity_id              BIGINT                                  NOT NULL,
    user_id                BIGINT                                  NOT NULL,
    reference              VARCHAR(50)                             NOT NULL,
    amount                 DECIMAL(14, 4)                          NOT NULL,
    balance                DECIMAL(14, 4),
    transaction_subject    INTEGER                                 NOT NULL,
    transaction_direction  INTEGER                                 NOT NULL,
    method                 INTEGER                                 NOT NULL,
    narration              VARCHAR(255),
    senders_bank_name      VARCHAR(100),
    senders_name           VARCHAR(100),
    senders_bank_code      VARCHAR(20),
    senders_account_number VARCHAR(20),
    transaction_date       TIMESTAMP                               NOT NULL,

    CONSTRAINT "pk_transactions" PRIMARY KEY (id)
);
CREATE TABLE transactions_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    transaction_id     BIGINT                                  NOT NULL,
    map_key            VARCHAR(100)                            NOT NULL,
    map_value          VARCHAR(300)                            NOT NULL,

    CONSTRAINT "pk_transactions_metadata" PRIMARY KEY (id)
);



CREATE TABLE activity_log
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255) NOT NULL,
    last_modified_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255) NOT NULL,
    version            INTEGER      NOT NULL DEFAULT 0,
    status             INTEGER      NOT NULL DEFAULT 1,

    activity_date      TIMESTAMP    NOT NULL,
    actor              VARCHAR(255) NOT NULL,
    action             VARCHAR(255) NOT NULL,
    entity             VARCHAR(255) NOT NULL,
    entity_id          BIGINT,
    application        VARCHAR(255) NOT NULL,
    activity           TEXT         NOT NULL,

    CONSTRAINT "pk_activity_log" PRIMARY KEY (id)
);

CREATE TABLE activity_log_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255) NOT NULL,
    last_modified_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255) NOT NULL,
    version            INTEGER      NOT NULL DEFAULT 0,
    status             INTEGER      NOT NULL DEFAULT 1,

    map_key            VARCHAR(255)       NOT NULL,
    map_value          TEXT       NOT NULL,
    activity_log_id    BIGINT       NOT NULL,
    CONSTRAINT "pk_activity_log_metadata" PRIMARY KEY (id),
    CONSTRAINT fk_activity_log
        FOREIGN KEY (activity_log_id) REFERENCES activity_log (id) ON DELETE CASCADE
);

-- Helpful indexes
CREATE INDEX idx_activity_log_entity_app
    ON activity_log (entity, application);

CREATE INDEX idx_activity_log_timestamp
    ON activity_log (activity_date);


CREATE UNIQUE INDEX IDX_TRANSACTIONS_REFERENCE ON transactions (reference);
CREATE INDEX IDX_TRANSACTIONS_entity_id_transaction_subject ON transactions (entity_id, transaction_subject);
CREATE INDEX IDX_TRANSACTIONS_USER_ID ON transactions (user_id);
CREATE INDEX IDX_TRANSACTIONS_TYPE_ID ON transactions (transaction_subject);
CREATE INDEX IDX_TRANSACTIONS_METHOD_ID ON transactions (method);