spring:
  application:
    name: users-service
  config:
    import: configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      label: ${GITHUB_BRANCH}
      profile: ${APP_PROFILE}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
      request-connect-timeout: 10
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 3000
        max-interval: 3500

encrypt:
  key: '${ENCRYPTION_KEY}'

hide:
  update:
    country: true
  get:
    countries: true


## TODO: DELETE
#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#    org.springframework.jdbc: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: TRACE
#spring.datasource.hikari.data-source-properties.logUnclosedConnections: true
#logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
#logging.level.com.zaxxer.hikari: TRACE
