
environment: dev-env

global:
  namespace: one-meristem-app
  serviceAccountName: app-spc-sa-dev
  create: false     # Prevent chart from trying to create it

networkpolicy:
  enabled: false

replicaCount: 2

image:
  repository: swr.af-south-1.myhuaweicloud.com/swr-repo-one-meristem-app-dev-env/report-service
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: huawei-swr-auth #relying on CCE's automatic injection

# Secret provider class
secretProviderClass:
  name: report-service-secrets
  provider: cce
  k8sSecretName: report-service-secrets


strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

resources:
  limits:
    cpu: "0.5"
    memory: 700Mi
  requests:
    cpu: "0.3"
    memory: 512Mi

volumeMounts:
  - name: huawei-csms-credentials
    mountPath: /mnt/secrets-store/report-service
    readOnly: true
  - name: report-data
    mountPath: /mnt/report
  - name: secret-volume
    mountPath: /etc/secrets-store/report-service
    readOnly: true

volumes:
  - name: report-data
    emptyDir: {}
  - name: huawei-csms-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: huawei-csms-credentials
        #csi.storage.k8s.io/provisioner-secret-name: huawei-csms-credentials
        #csi.storage.k8s.io/provisioner-secret-namespace: one-meristem-app
  - name: secret-volume
    secret:
      secretName: credentials


env:
  COMPANY_NAME: "Meristem Securities Limited"
  DATA_PRIVACY_POLICY_URL: "https://www.onemerristem.merristem.com"
  GREEN_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Green_Logo.png"
  WHITE_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_White_Logo.png"
  FINANCE_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Finance_Logo.png"
  GITHUB_BRANCH: "dev_env" #github branch
  APP_PROFILE: "dev"
  SERVER_PORT: "20050"
  ONE_APP_SERVER_URL: "https://" #placeholder for the EIP IP
  ONE_APP_EMAIL: "hello@onemeristem.meristemng.com"
  ADMIN_USERNAME: "admin"
  CONFIG_SERVER_URI: "http://config-server:20000/config"
  CREDIT_SWITCH_LOGIN_ID: "315497"
  CREDIT_SWITCH_SMS_MERCHANT_NAME: "Meristem Securities Limited"
  CREDIT_SWITCH_SMS_BASEURL: "http://176.58.99.160:9014/api/v1/sms/send"
  CREDIT_SWITCH_SMS_SENDER_ID: "Meristem"
  REPORT_SERVICE_HOSTNAME: "report-service"
  REPORT_SERVICE_URI: "http://report-service:20050"
  CONSUL_HOST: consul
  USER_SERVICE_URI: "http://users-service:20020"
  TRUSTEES_CLIENT_ID: trustees-service
  HUAWEI_OBS_UNSTRUCTURED_BUCKET: "obs-unstructured-logo-one-meristem-dev-env"
  MERISTEM_GREEN_LOGO: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Green_Logo.png"
  SUPPORT_PHONE: "0700-MERISTEM"
  SUPPORT_EMAIL: "support@onemeristem.com"

secretEnv:
  ADMIN_PASSWORD:
    secretName: credentials
    secretKey: key3
  ENCRYPTION_KEY:
    secretName: credentials
    secretKey: key4
  DB_SERVER:
    secretName: huawei-csms-credentials
    secretKey: DB_SERVER
  REPORT_DB_NAME:
    secretName: huawei-csms-credentials
    secretKey: REPORT_DB_NAME
  REPORT_DB_USERNAME:
    secretName: huawei-csms-credentials
    secretKey: REPORT_DB_USERNAME
  REPORT_DB_PASSWORD:
    secretName: huawei-csms-credentials
    secretKey: REPORT_DB_PASSWORD
  KAFKA_HOST_URL:
    secretName: huawei-csms-credentials
    secretKey: KAFKA_HOST_URL
  REDIS_HOST:
    secretName: huawei-csms-credentials
    secretKey: REDIS_HOST
  REDIS_PASSWORD:
    secretName: huawei-csms-credentials
    secretKey: REDIS_PASSWORD
  MAILER_HOST:
    secretName: credentials
    secretKey: key5
  MAILER_USERNAME:
    secretName: credentials
    secretKey: key6
  MAILER_PASSWORD:
    secretName: credentials
    secretKey: key7
  CREDIT_SWITCH_PUBLIC_KEY:
    secretName: credentials
    secretKey: key8
  CREDIT_SWITCH_PRIVATE_KEY:
    secretName: credentials
    secretKey: key9
  CREDIT_SWITCH_SMS_PASSWORD:
    secretName: credentials
    secretKey: key10
  H2_PASSWORD:
    secretName: credentials
    secretKey: key13
  TRUSTEES_CLIENT_SECRET: 
    secretName: credentials
    secretKey: key16

#PVC configuration
# pvc:
#   name: report-service-pvc-evs
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: csi-disk-topology
#   volumeMode: Filesystem


# HorizontalPodAutoscaler configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70


# service configuration
service:
  type: ClusterIP
  name: report-service
  port: 8082
  targetPort: 20050

