# apiVersion: v1
# kind: Service
# metadata:
#   name: config-server
#   namespace: one-meristem-app
#   labels:
#     app: config-server
# spec:
#   type: ClusterIP
#   ports:
#     - name: config-server
#       port: 20000
#       protocol: TCP
#       targetPort: 20000
#   selector:
#     app: config-server


apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "config-server.name" . }}
spec:
  selector:
    app: {{ include "config-server.name" . }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}



