# apiVersion: v1
# kind: Service
# metadata:
#   name: notification-service
#   namespace: one-meristem-app
#   labels:
#     app: notification-service
# spec:
#   type: ClusterIP
#   ports:
#     - name: notification-service
#       port: 20030
#       protocol: TCP
#       targetPort: 20030
#   selector:
#     app: notification-service


apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "notification-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "notification-service.name" . }}
