# Build environment
FROM maven:3.9.8-eclipse-temurin-21-alpine AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn -B -f./pom.xml package -DskipTests

# Production packaging
FROM openjdk:21-jdk
LABEL maintainer="Kingsley Godwin <kingsleygodwin@meristemng.com>"

WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/notification-service*.jar /app/notification-service.jar
EXPOSE 20030
ENTRYPOINT sh -c "java -jar notification-service.jar"
