spring:
  flyway:
    locations: classpath:db/migration/postgres
    validate-migration-naming: true

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh,restart,health'        
  endpoint:
    restart:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true

