spring:
  kafka:
    consumer:
      group-id: ${spring.cloud.config.profile}-core-service

  cloud:
    consul:
      discovery:
        health-check-path: ${one-app.core-service.context-path}/actuator/health
        enabled: true
        fail-fast: true
        catalogServicesWatch:
          enabled: false
        hostname: ${USER_SERVICE_HOSTNAME}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-interval: 60s
      host: ${CONSUL_HOST}

server:
  port: 20060
  servlet:
    context-path: ${one-app.core-service.context-path}

one-app:
  core-service:
    company-name: ${COMPANY_NAME}
    data-privacy-policy-url: ${DATA_PRIVACY_POLICY_URL}
    logo-url: ${GREEN_LOGO_URL}
    white-logo-url: ${WHITE_LOGO_URL}
    finance-logo-url: ${FINANCE_LOGO_URL}