spring:

  modulith:
    runtime:
      flyway:
        enabled: true
  flyway:
    locations:
       - classpath:db/migration/__root
       - classpath:db/migration/notifications
       - classpath:db/migration/wealth
       
  datasource:
    url: ${DB_SERVER}/${CORE_DB_NAME}
    password: ${CORE_DB_PASSWORD}
    username: ${CORE_DB_USERNAME}
    driver-class-name: org.postgresql.Driver

