server:
  port: 20010

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus,info,gateway,circuitbreakerevents'
  endpoint:
    health:
      show-details: always
      access: read_only
    prometheus:
      access: none
    gateway:
      access: read_only
  health:
    mail:
      enabled: false

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "http://localhost:*"
                  - "http://127.0.0.1:*"
                  - "https://localhost:*"
                  - "https://127.0.0.1:*"
