spring:
  cloud:
    gateway:
      routes:
        - id: ${one-app.users-service.application-name}
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=${one-app.users-service.context-path}/**

        - id: ${one-app.wallet-service.application-name}
          uri: ${WALLET_SERVICE_URI}
          predicates:
            - Path=${one-app.wallet-service.context-path}/**

        - id: ${one-app.report-service.application-name}
          uri: ${REPORT_SERVICE_URI}
          predicates:
            - Path=${one-app.report-service.context-path}/**

        - id: ${one-app.trusties-service.application-name}
          uri: ${TRUSTIES_SERVICE_URI}
          predicates:
            - Path=${one-app.trusties-service.context-path}/**
