spring:

  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${NOTIFICATION_DB_NAME}
    password: ${NOTIFICATION_DB_PASSWORD}
    username: ${NOTIFICATION_DB_USERNAME}
    driver-class-name: org.postgresql.Driver

