spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${USERS_DB_PORT:5432}/${USERS_DB_NAME}
    password: ${REPORT_DB_PASSWORD}
    username: ${REPORT_DB_USERNAME}
    driver-class-name: org.postgresql.Driver