spring:

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT:5432}/${TRUSTEES_DB_NAME}
    password: ${TRUSTEES_DB_PASSWORD}
    username: ${TRUSTEES_DB_USERNAME}
    driver-class-name: org.postgresql.Driver

