spring:
  kafka:
    consumer:
      group-id: ${spring.cloud.config.profile}-users-service

  cloud:
    consul:
      discovery:
        metadata:
          contextPath: ${one-app.users-service.context-path}
        health-check-path: ${one-app.users-service.context-path}/actuator/health
        enabled: true
        fail-fast: true
        catalogServicesWatch:
          enabled: false
        hostname: ${USER_SERVICE_HOSTNAME}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-interval: 60s
      host: ${CONSUL_HOST}

server:
  port: 20020
  servlet:
    context-path: ${one-app.users-service.context-path}

one-app:
  users-service:
    dbLocation: "/Users/kingsleygodwin/Downloads/GeoLite2-City_20250916/GeoLite2-City.mmdb"
    smile-id:
      server-ips: ${SMILE_ID_PROD_SERVER_IPS}
      api-key: ${SMILE_ID_PROD_API_KEY}
      partner-id: ${SMILE_ID_PARTNER_ID}
      url: ${SMILE_ID_PROD_LAMBDA_URL}
      callback-url: ${SMILE_ID_PROD_CALLBACK_URL}
      is-single-use: true
      expires-at: 2 # in days
      client-name: SmileID
    company-name: ${COMPANY_NAME}
    data-privacy-policy-url: ${DATA_PRIVACY_POLICY_URL}
    logo-url: ${GREEN_LOGO_URL}
    white-logo-url: ${WHITE_LOGO_URL}
    finance-logo-url: ${FINANCE_LOGO_URL}
    okhi:
      server-ips: ${OKHI_DEV_AND_PROD_WHITELIST_IP}
      header-value: ${OKHI_HEADER_VALUE}

  mobile-service:
    secret: ${MOBILE_SECRET}
    name: MobileService
  notification-service:
    secret: ${NOTIFICATION_SECRET}
    name: NotificationService
  trusties-service:
    secret: ${TRUSTIES_SECRET}
    name: TrustiesService


#geoip:
#  db:
#    location: ${GEOIP_DB_LOCATION}
#
