spring:
  kafka:
    consumer:
      group-id: ${spring.cloud.config.profile}-users-service

  cloud:
    consul:
      discovery:
        health-check-path: ${one-app.users-service.context-path}/actuator/health
        enabled: true
        fail-fast: true
        catalogServicesWatch:
          enabled: false
        hostname: ${USER_SERVICE_HOSTNAME}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-interval: 60s
      host: ${CONSUL_HOST}

server:
  port: 20020
  servlet:
    context-path: ${one-app.users-service.context-path}

one-app:
  users-service:
    smile-id:
      server-ips: ${SMILE_ID_PROD_SERVER_IPS}
      api-key: ${SMILE_ID_PROD_API_KEY}
      partner-id: ${SMILE_ID_PARTNER_ID}
      url: ${SMILE_ID_PROD_LAMBDA_URL}
      callback-url: ${SMILE_ID_PROD_CALLBACK_URL}
      is-single-use: true
      expires-at: 2 # in days