spring:
  datasource:
    url: jdbc:postgresql://${USERS_DB_ENDPOINT}:${USERS_DB_PORT:5432}/${USERS_DB_NAME}
    password: ${WALLET_DB_PASSWORD}
    username: ${WALLET_DB_USERNAME}
    driver-class-name: org.postgresql.Driver