spring:
  kafka:
    consumer:
      group-id: ${spring.cloud.config.profile}-wallet-service

  cloud:
    consul:
      discovery:
        health-check-path: ${one-app.wallet-service.context-path}/actuator/health
        enabled: true
        fail-fast: true
        catalogServicesWatch:
          enabled: false
        hostname: ${WALLET_SERVICE_HOSTNAME}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-interval: 60s
      host: ${CONSUL_HOST}

server:
  port: 20040
  servlet:
    context-path: ${one-app.wallet-service.context-path}

one-app:
  wallet-service:
    wema:
      integration-name: 'Wema Integration'
      url: ${WEMA_API_URL}