name: meristem-one-app
services:

  # Applications
  config-server:
    container_name: config-server
    ports:
      - "20000:20000"
    platform: linux/amd64
    env_file:
      - ../../../../otherFiles/mis/one-meristem-app-env.env
    image: config-server:latest
    networks:
      - backend

  gateway-service:
    container_name: gateway-service
    ports:
      - "20010:20010"
    platform: linux/amd64
    env_file:
      - ../../../../otherFiles/mis/one-meristem-app-env.env
    image: gateway-service:latest
    depends_on:
      - config-server
    networks:
      - backend


networks:
  backend:
    driver: bridge
