
CREATE TABLE permissions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE requirements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    display_name       VARCHAR(50)                             NOT NULL,
    requirement_name   VARCHAR(50)                             NOT NULL,
    mandatory          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_requirements PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_permissions
(
    roles_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

CREATE TABLE user_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    url                VARCHAR(1000)                           NOT NULL,
    requirement_id     BIGINT,
    user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_document PRIMARY KEY (id)
);

CREATE TABLE user_onboarding
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    completed          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_onboarding PRIMARY KEY (id)
);

CREATE TABLE user_profile
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    picture_url        VARCHAR(500),
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status             INT DEFAULT 1                           NOT NULL,
    email                VARCHAR(200)                            NOT NULL,
    first_name           VARCHAR(150)                            NOT NULL,
    last_name            VARCHAR(150)                            NOT NULL,
    middle_name          VARCHAR(150),
    password             VARCHAR(200)                            NOT NULL,
    phone_number         VARCHAR(50)                             NOT NULL,
    referral_code        VARCHAR(100),
    onboarding_completed BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (users_id, roles_id)
);

CREATE TABLE otp_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    code               INT                                     NOT NULL,
    user_id            VARCHAR(200)                            NOT NULL,
    otp_type           INT                                     NOT NULL,
    verified           BOOLEAN DEFAULT FALSE                   NOT NULL,
    expires_at         TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_otpverification PRIMARY KEY (id)
);


CREATE TABLE address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    house_address VARCHAR(150)                            NOT NULL,
    city          VARCHAR(100)                            NOT NULL,
    postal_code   VARCHAR(10)                             NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE otp_verification
    ADD CONSTRAINT uc_otpver_code_uid_ot UNIQUE (code, user_id, otp_type);

CREATE INDEX idx_otpver_uid_ot ON otp_verification (user_id, otp_type);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_user_id_onbaording ON user_onboarding(user_id);


ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permissions_id) REFERENCES permissions (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);


ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_users FOREIGN KEY (users_id) REFERENCES users (id);

INSERT INTO requirements (
    id, created_date, created_by, last_modified_date, last_modified_by, version, status,
    display_name, requirement_name, mandatory
)
VALUES
    (1, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'BVN Verification', 'BVN', TRUE),
    (2, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'Address Verification', 'PROOF_OF_ADDRESS', TRUE),
    (3, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'ID Verification', 'GOVERNMENT_ISSUED_ID', TRUE);