CREATE TABLE aml_search
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL, -- 0 - PENDING, 1 - COMPLETED, 2- FAILED
    subject_type       VARCHAR(50),                                                         -- USER, BUSINESS, TRUST
    subject_reference  VARCHAR(100),                                                        -- user_id, bvn, nin, etc, email
    search_type        VARCHAR(20),                                                         -- PEP, SANCTION, BOTH
    vendor             VARCHAR(50),                                                         -- vendor name PASTEL or whatever
    completed_date     TIMESTAMP,

    CONSTRAINT pk_aml_search PRIMARY KEY (id)

);


CREATE TABLE aml_result
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL,

    search_id          BIGINT REFERENCES aml_search (id),
    vendor_id          VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    dobs               VARCHAR(255), -- comma separated year-month-day
    gender             VARCHAR(20)                             ,

    entity_type        VARCHAR(50),  -- e.g., 'Person', 'Organization'
    countries          VARCHAR(255), -- comma separated
    aliases            VARCHAR(255), -- comma separated

    pep                BOOLEAN,
    sanctioned         BOOLEAN,

    photo              TEXT,
    political_party    VARCHAR(300), -- comma separated
    education          CLOB,
    position           CLOB,
    confidence_score   INT                                     NOT NULL,

    vendor_dataset     CLOB,

    CONSTRAINT pk_aml_result PRIMARY KEY (id),
    CONSTRAINT fk_aml_result_on_search_id FOREIGN KEY (search_id) REFERENCES aml_search (id)

);


CREATE TABLE aml_decision
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL, -- 0 FAILED, 1 SUCCESSFUL, 2 INVALID

    search_id          BIGINT,
    result_id          BIGINT,

    decision           VARCHAR(20),                                                         -- MATCH, NO_MATCH, REVIEW
    decided_by         VARCHAR(100),
    reason             TEXT,

    CONSTRAINT pk_aml_decision PRIMARY KEY (id),
    CONSTRAINT fk_aml_decision_on_search_id FOREIGN KEY (search_id) REFERENCES aml_search (id),
    CONSTRAINT fk_aml_decision_on_result_id FOREIGN KEY (result_id) REFERENCES aml_result (id)
);
