{{- if and .Values.pvc.enabled .Values.pvc.useExistingBucket }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-service-obs-pv-{{ .Values.environment }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: obs.csi.everest.io
    volumeHandle: obs-microservice-storage-one-meristem-app-{{ .Values.environment }}
    nodeStageSecretRef:
    name: huawei-credentials-obs-ak
    namespace: one-meristem-app
    volumeAttributes:
      everest.io/obs-volume-type: STANDARD
      storage.kubernetes.io/csiProvisionerIdentity: obs.csi.everest.io
{{- end }}
