# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: users-service-pvc-evs
#   namespace: one-meristem-app
#   annotations:
#     everset.io/disk-volume-type: SSD
#     #everest.io/crypt-key-id: <key_id>   #Input your key id here
#     #everest.io/csi.charging-mode: prePaid
#     #everest.io/csi.period-type: year
#     #everest.io/csi.period-num: 1
#     failure-domain.beta.kubernetes.io/region: af-south-1
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: csi-disk
#   volumeName: pv-evs

{{/*
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Values.pvc.name }}
#   namespace: {{ .Values.global.namespace | default .Release.Namespace }}
# spec:
#   accessModes: {{ toYaml .Values.pvc.accessModes | nindent 4 }}
#   resources:
#     requests:
#       storage: {{ .Values.pvc.resources.requests.storage }}
#   storageClassName: {{ .Values.pvc.storageClassName }}
#   volumeMode: {{ .Values.pvc.volumeMode | default "Filesystem" }}
*/}}

{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (include "users-service.fullname" .) }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "500Mi" }}
  storageClassName: {{ .Values.pvc.storageClassName | default "csi-obs" }}
  volumeMode: Filesystem
{{- end }}
