apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    serviceAccountName: {{ .Values.global.serviceAccountName | default "app-spc-sa" }}
    objects: |
      - objectName: "db-admin-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: postgres_password
          - path: username
            objectAlias: postgres_user

      - objectName: "redis-mobile-backend-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: connection_string
            objectAlias: redis_host
          - path: password
            objectAlias: redis_password
          - path: host  
            objectAlias: redis_endpoint_without_port
          - path: port 
            objectAlias: redis_port

      - objectName: "redis-middleware-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: connection_string
            objectAlias: redis_middleware_host
          - path: password
            objectAlias: redis_middleware_password
          - path: host  
            objectAlias: redis_middleware_endpoint_without_port
          - path: port 
            objectAlias: redis_middleware_port

      - objectName: "kafka-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: kafka_host_url
            objectAlias: kafka_host_url
          - path: kafka_password
            objectAlias: kafka_password

      - objectName: "db-users_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: users_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: users_db_password
          - path: username
            objectAlias: users_db_username

      - objectName: "db-wallet_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: wallet_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: wallet_db_password
          - path: username
            objectAlias: wallet_db_username

      - objectName: "db-report_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: report_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: report_db_password
          - path: username
            objectAlias: report_db_username

      - objectName: "db-trustees_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: trustees_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: trustees_db_password
          - path: username
            objectAlias: trustees_db_username

  secretObjects: 
    - secretName: {{ .Values.secretProviderClass.k8sSecretName }}
      type: Opaque
      data: 
        - objectName: db_server
          key: DB_SERVER
        - objectName: postgres_password
          key: POSTGRES_PASSWORD
        - objectName: postgres_user
          key: POSTGRES_USER
        - objectName: redis_host
          key: REDIS_HOST
        - objectName: redis_password
          key: REDIS_PASSWORD
        - objectName: redis_endpoint_without_port
          key: REDIS_ENDPOINT_WITHOUT_PORT
        - objectName: redis_port
          key: REDIS_PORT
        - objectName: redis_middleware_host
          key: REDIS_MIDDLEWARE_HOST
        - objectName: redis_middleware_password
          key: REDIS_MIDDLEWARE_PASSWORD
        - objectName: redis_middleware_endpoint_without_port
          key: REDIS_MIDDLEWARE_ENDPOINT_WITHOUT_PORT
        - objectName: redis_middleware_port
          key: REDIS_MIDDLEWARE_PORT
        - objectName: kafka_host_url
          key: KAFKA_HOST_URL
        - objectName: kafka_password
          key: KAFKA_PASSWORD
        - objectName: users_db_name
          key: USERS_DB_NAME
        - objectName: users_db_password
          key: USERS_DB_PASSWORD
        - objectName: users_db_username
          key: USERS_DB_USERNAME
        - objectName: wallet_db_name
          key: WALLET_DB_NAME
        - objectName: wallet_db_password
          key: WALLET_DB_PASSWORD
        - objectName: wallet_db_username
          key: WALLET_DB_USERNAME
        - objectName: report_db_name
          key: REPORT_DB_NAME
        - objectName: report_db_password
          key: REPORT_DB_PASSWORD
        - objectName: report_db_username
          key: REPORT_DB_USERNAME
        - objectName: trustees_db_name
          key: TRUSTEES_DB_NAME
        - objectName: trustees_db_password
          key: TRUSTEES_DB_PASSWORD
        - objectName: trustees_db_username
          key: TRUSTEES_DB_USERNAME
