{{/*
# {{- if and .Values.obsCredentials.enabled .Values.obsCredentials.accessKey .Values.obsCredentials.secretKey }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: everest-secret
#   namespace: kube-system # Must be in kube-system for CSI driver
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     argocd.argoproj.io/sync-options: Prune=false # Prevent ArgoCD from deleting this due to using Kube-System namespace in the shared-resource folder which has one-meristem-namespace
#     argocd.argoproj.io/sync-wave: "-1"
# type: Opaque
# data:
#   access-key: {{ .Values.obsCredentials.accessKey | b64enc  | quote }}
#   secret-key: {{ .Values.obsCredentials.secretKey | b64enc  | quote }}
#   project.id: {{ .Values.huaweiCloudStorage.projectId | b64enc | quote }}
#   region: {{ .Values.huaweiCloudStorage.region | b64enc | quote }}
# {{- end }}
*/}}
