# =============================================================================
# image-pull-secret.yaml
# Huawei SWR image pull secret
# Allows Kubernetes to pull images from the private SWR registry
# dockerconfigjson injected via ArgoCD app set from CD pipeline
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: huawei-swr-auth
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson | quote }}
