apiVersion: v1
kind: Secret
metadata:
  name: huawei-swr-auth
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson | quote }}
