#OBS Access Secret

# {{- if .Values.obsSecret.enabled }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.obsSecret.name }}
#   namespace: {{ .Values.obsSecret.namespace }}
#   labels:
#     secret.kubernetes.io/used-by: csi
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
#     argocd.argoproj.io/sync-options: Prune=false  
#     argocd.argoproj.io/compare-options: IgnoreExtraneous  
# type: cfe/secure-opaque
# data: 
#   accessKey: {{ .Values.obsSecret.data.accessKey }}
#   secretKey: {{ .Values.obsSecret.data.secretKey }}
# {{- end }}

#N.B - You can get these values yourself with:
# echo -n "<your_AK_here>" | base64
# echo -n "<your_SK_here>" | base64


#OBS Access Secret
{{- if .Values.obsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.obsSecret.name }}
  namespace: {{ .Values.namespace | default "one-meristem-app" }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
data:
  access.key: {{ .Values.obsSecret.accessKey }}
  secret.key: {{ .Values.obsSecret.secretKey }}
{{- end }}
