# =============================================================================
# obs-secret.yaml
# Huawei OBS (Object Storage Service) credentials
# Used by services that read/write files to OBS buckets
# Raw values injected via ArgoCD app set from CD pipeline
# =============================================================================

#OBS Access Secret
{{- if .Values.obsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.obsSecret.name }}
  namespace: {{ .Values.namespace | default "one-meristem-app" }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
data:
  access.key: {{ required "OBS access key is missing!" .Values.obsSecret.data.accessKey | quote }}
  secret.key: {{ required "OBS secret key is missing!" .Values.obsSecret.data.secretKey | quote }}
{{- end }}
