{{- if .Values.huaweiCloudStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: paas.longaksk
  namespace: kube-system  # Must be in kube-system for CSI driver
type: Opaque
data:
  access.key: {{ .Values.huaweiCloudStorage.accessKey | b64enc | quote }}
  secret.key: {{ .Values.huaweiCloudStorage.secretKey | b64enc | quote }}
  project.id: {{ .Values.huaweiCloudStorage.projectId | b64enc | quote }}
  region: {{ .Values.huaweiCloudStorage.region | b64enc | quote }}
{{- end }}
