# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: sa-secret-rolebinding
#   namespace: one-meristem-app
# subjects:
#   - kind: ServiceAccount
#     name: app-spc-sa
#     namespace: one-meristem-app
# roleRef:
#   kind: Role
#   name: sa-secret-role
#   apiGroup: rbac.authorization.k8s.io


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io
