# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: huawei-csms-credentials
#   namespace: one-meristem-app
# spec:
#   provider: cce     # The value is fixed at cce.
#   parameters:
#    # Reference a secret in CSMS.
#     objects: |
#           - objectName: "db-admin-secret-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: endpoint
#                 objectAlias: db_server
#               - path: password
#                 objectAlias: postgres_password
#               - path: username
#                 objectAlias: postgres_user

#           - objectName: "redis-credentials-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: connection_string
#                 objectAlias: redis_host
#               - path: password
#                 objectAlias: redis_password
#               -path: host  
#                 objectAlias: redis_endpoint_without_port
#               -path: port
#                 objectAlias: redis_port

#           - objectName: "kafka-credentials-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: kafka_host_url
#                 objectAlias: kafka_host_url
#               - path: kafka_password
#                 objectAlias: kafka_password

#           - objectName: "db-notification_service-secret-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: database 
#                 objectAlias: notificattion_db_name
#               -path: endpoint
#                 objectAlias: db_server
#               -path: password
#                 objectAlias: notification_db_password
#               path: username 
#                 objectAlias: notification_db_username

#           - objectName: "db-users_service-secret-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: database
#                 objectAlias: users_db_name
#               - path: endpoint
#                 objectAlias: db_server
#               - path: password
#                 objectAlias: users_db_password
#               - path: username
#                 objectAlias: users_db_username

#           - objectName: "db-wallet_service-secret-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: database
#                 objectAlias: wallet_db_name
#               - path: endpoint
#                 objectAlias: db_server
#               - path: password
#                 objectAlias: wallet_db_password
#               - path: username
#                 objectAlias: wallet_db_username

#           - objectName: "db-report_service-secret-one-meristem-dev-env"
#             objectVersion: "latest"
#             objectType: "csms"
#             jmesPath:
#               - path: database
#                 objectAlias: report_db_name
#               - path: endpoint
#                 objectAlias: db_server
#               - path: password
#                 objectAlias: report_db_password
#               - path: username
#                 objectAlias: report_db_username


# # Create a CCE secret based on the CSMS secret and mount the secret to a pod.
#     secretObjects:
#       - secretName: huawei-csms-credentials
#     # Specify the name of the secret to be created in the Kubernetes cluster.
#       - type: Opaque
#         data:
#           # Specify the key-value pairs to be stored in the secret.
#           - objectName: db_server
#             key: DB_SERVER
#           - objectName: postgres_password
#             key: POSTGRES_PASSWORD
#           - objectName: postgres_user
#             key: POSTGRES_USER
#           - objectName: redis_host
#             key: REDIS_HOST
#           - objectName: redis_password
#             key: REDIS_PASSWORD
#           - objectName: redis_endpoint_without_port
#             key: REDIS_ENDPOINT_WITHOUT_PORT
#           - objectName: redis_port
#             key: REDIS_PORT
#           - objectName: kafka_host_url
#             key: KAFKA_HOST_URL
#           - objectName: kafka_password
#             key: KAFKA_PASSWORD
#           - objectName: notificattion_db_name
#             key: NOTIFICATION_DB_NAME
#           - objectName: db_server
#             key: DB_SERVER
#           - objectName: notification_db_password
#             key: NOTIFICATION_DB_PASSWORD
#           - objectName: notification_db_username
#             key: NOTIFICATION_DB_USERNAME
#           - objectName: users_db_name
#             key: USERS_DB_NAME
#           - objectName: db_server
#             key: DB_SERVER
#           - objectName: users_db_password
#             key: USERS_DB_PASSWORD
#           - objectName: users_db_username
#             key: USERS_DB_USERNAME
#           - objectName: wallet_db_name
#             key: WALLET_DB_NAME
#           - objectName: db_server
#             key: DB_SERVER
#           - objectName: wallet_db_password
#             key: WALLET_DB_PASSWORD
#           - objectName: wallet_db_username
#             key: WALLET_DB_USERNAME
#           - objectName: report_db_name
#             key: REPORT_DB_NAME
#           - objectName: db_server
#             key: DB_SERVER
#           - objectName: report_db_password
#             key: REPORT_DB_PASSWORD
#           - objectName: report_db_username
#             key: REPORT_DB_USERNAME
#     # Specify the key-value pairs to be stored in the secret.
#     # The key is the name of the field in the secret, and the value is the alias of the field in the CSMS secret.
#     # The value of the field in the secret will be replaced with the value of the field in the CSMS secret.
#     # For example, if the CSMS secret has a field named "username", and you want to store it in the secret with the key "db_username",
#     # you can specify "db_username: username" in the secretObjects section.
#     # The value of the field in the secret will be replaced with the value of the field in the CSMS secret.


# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: {{ .Values.secretProviderClass.name }}
#   namespace: {{ .Values.namespace }}
# spec:
#   provider: {{ .Values.secretProviderClass.provider }}
#   parameters:
#   # Reference a secret in CSMS.
#     objects: |
#       - objectName: "db-admin-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: postgres_password
#           - path: username
#             objectAlias: postgres_user

#       - objectName: "redis-mobile-backend-credentials-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: connection_string
#             objectAlias: redis_host
#           - path: password
#             objectAlias: redis_password
#           - path: host  
#             objectAlias: redis_endpoint_without_port
#           - path: port
#             objectAlias: redis_port

#       - objectName: "redis-middleware-credentials-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: connection_string
#             objectAlias: redis_middleware_host
#           - path: password
#             objectAlias: redis_middleware_password
#           - path: host  
#             objectAlias: redis_middleware_endpoint_without_port
#           - path: port
#             objectAlias: redis_middleware_port

#       - objectName: "kafka-credentials-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: kafka_host_url
#             objectAlias: kafka_host_url
#           - path: kafka_password
#             objectAlias: kafka_password

#       - objectName: "db-notification_service-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: database 
#             objectAlias: notificattion_db_name
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: notification_db_password
#           - path: username 
#             objectAlias: notification_db_username

#       - objectName: "db-users_service-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: database
#             objectAlias: users_db_name
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: users_db_password
#           - path: username
#             objectAlias: users_db_username

#       - objectName: "db-wallet_service-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: database
#             objectAlias: wallet_db_name
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: wallet_db_password
#           - path: username
#             objectAlias: wallet_db_username

#       - objectName: "db-report_service-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: database
#             objectAlias: report_db_name
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: report_db_password
#           - path: username
#             objectAlias: report_db_username

#       - objectName: "db-trustees_service-secret-one-meristem-dev-env"
#         objectVersion: "latest"
#         objectType: "csms"
#         jmesPath:
#           - path: database
#             objectAlias: trustees_db_name
#           - path: endpoint
#             objectAlias: db_server
#           - path: password
#             objectAlias: trustees_db_password
#           - path: username
#             objectAlias: trustees_db_username
        

# # Create a CCE secret based on the CSMS secret and mount the secret to a pod.
#   secretObjects: 
#     - secretName: {{ .Values.secretProviderClass.k8sSecretName }}
#     # Specify the name of the secret to be created in the Kubernetes cluster.
#       type: Opaque
#       data: 
#       # Specify the key-value pairs to be stored in the secret.
#         - objectName: db_server
#           key: DB_SERVER
#         - objectName: postgres_password
#           key: POSTGRES_PASSWORD
#         - objectName: postgres_user
#           key: POSTGRES_USER
#         - objectName: redis_host
#           key: REDIS_HOST
#         - objectName: redis_password
#           key: REDIS_PASSWORD
#         - objectName: redis_endpoint_without_port
#           key: REDIS_ENDPOINT_WITHOUT_PORT
#         - objectName: redis_port
#           key: REDIS_PORT
#         - objectName: redis_middleware_host
#           key: REDIS_MIDDLEWARE_HOST
#         - objectName: redis_middleware_password
#           key: REDIS_MIDDLEWARE_PASSWORD
#         - objectName: redis_middleware_endpoint_without_port
#           key: REDIS_MIDDLEWARE_ENDPOINT_WITHOUT_PORT
#         - objectName: redis_middleware_port
#           key: REDIS_MIDDLEWARE_PORT
#         - objectName: kafka_host_url
#           key: KAFKA_HOST_URL
#         - objectName: kafka_password
#           key: KAFKA_PASSWORD
#         - objectName: notificattion_db_name
#           key: NOTIFICATION_DB_NAME
#         - objectName: notification_db_password
#           key: NOTIFICATION_DB_PASSWORD
#         - objectName: notification_db_username
#           key: NOTIFICATION_DB_USERNAME
#         - objectName: users_db_name
#           key: USERS_DB_NAME
#         - objectName: users_db_password
#           key: USERS_DB_PASSWORD
#         - objectName: users_db_username
#           key: USERS_DB_USERNAME
#         - objectName: wallet_db_name
#           key: WALLET_DB_NAME
#         - objectName: wallet_db_password
#           key: WALLET_DB_PASSWORD
#         - objectName: wallet_db_username
#           key: WALLET_DB_USERNAME
#         - objectName: report_db_name
#           key: REPORT_DB_NAME
#         - objectName: report_db_password
#           key: REPORT_DB_PASSWORD
#         - objectName: report_db_username
#           key: REPORT_DB_USERNAME
#         - objectName: trustees_db_name
#           key: TRUSTEES_DB_NAME
#         - objectName: trustees_db_password
#           key: TRUSTEES_DB_PASSWORD
#         - objectName: trustees_db_username
#           key: TRUSTEES_DB_USERNAME
#     # Specify the key-value pairs to be stored in the secret.
#     # The key is the name of the field in the secret, and the value is the alias of the field in the CSMS secret.
#     # The value of the field in the secret will be replaced with the value of the field in the CSMS secret.
#     # For example, if the CSMS secret has a field named "username", and you want to store it in the secret with the key "db_username",
#     # you can specify "db_username: username" in the secretObjects section.
#     # The value of the field in the secret will be replaced with the value of the field in the CSMS secret.




apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    objects: |
      - objectName: "db-admin-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: postgres_password
          - path: username
            objectAlias: postgres_user

      - objectName: "redis-mobile-backend-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: connection_string
            objectAlias: redis_host
          - path: password
            objectAlias: redis_password
          - path: host  
            objectAlias: redis_endpoint_without_port
          - path: port
            objectAlias: redis_port

      - objectName: "redis-middleware-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: connection_string
            objectAlias: redis_middleware_host
          - path: password
            objectAlias: redis_middleware_password
          - path: host  
            objectAlias: redis_middleware_endpoint_without_port
          - path: port
            objectAlias: redis_middleware_port

      - objectName: "kafka-credentials-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: kafka_host_url
            objectAlias: kafka_host_url
          - path: kafka_password
            objectAlias: kafka_password

      - objectName: "db-notification_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database 
            objectAlias: notificattion_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: notification_db_password
          - path: username 
            objectAlias: notification_db_username

      - objectName: "db-users_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: users_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: users_db_password
          - path: username
            objectAlias: users_db_username

      - objectName: "db-wallet_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: wallet_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: wallet_db_password
          - path: username
            objectAlias: wallet_db_username

      - objectName: "db-report_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: report_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: report_db_password
          - path: username
            objectAlias: report_db_username

      - objectName: "db-trustees_service-secret-one-meristem-app-{{ .Values.environment }}"
        objectVersion: "latest"
        objectType: "csms"
        jmesPath:
          - path: database
            objectAlias: trustees_db_name
          - path: endpoint
            objectAlias: db_server
          - path: password
            objectAlias: trustees_db_password
          - path: username
            objectAlias: trustees_db_username

  secretObjects: 
    - secretName: {{ .Values.secretProviderClass.k8sSecretName }}
      type: Opaque
      data: 
        - objectName: db_server
          key: DB_SERVER
        - objectName: postgres_password
          key: POSTGRES_PASSWORD
        - objectName: postgres_user
          key: POSTGRES_USER
        - objectName: redis_host
          key: REDIS_HOST
        - objectName: redis_password
          key: REDIS_PASSWORD
        - objectName: redis_endpoint_without_port
          key: REDIS_ENDPOINT_WITHOUT_PORT
        - objectName: redis_port
          key: REDIS_PORT
        - objectName: redis_middleware_host
          key: REDIS_MIDDLEWARE_HOST
        - objectName: redis_middleware_password
          key: REDIS_MIDDLEWARE_PASSWORD
        - objectName: redis_middleware_endpoint_without_port
          key: REDIS_MIDDLEWARE_ENDPOINT_WITHOUT_PORT
        - objectName: redis_middleware_port
          key: REDIS_MIDDLEWARE_PORT
        - objectName: kafka_host_url
          key: KAFKA_HOST_URL
        - objectName: kafka_password
          key: KAFKA_PASSWORD
        - objectName: notificattion_db_name
          key: NOTIFICATION_DB_NAME
        - objectName: notification_db_password
          key: NOTIFICATION_DB_PASSWORD
        - objectName: notification_db_username
          key: NOTIFICATION_DB_USERNAME
        - objectName: users_db_name
          key: USERS_DB_NAME
        - objectName: users_db_password
          key: USERS_DB_PASSWORD
        - objectName: users_db_username
          key: USERS_DB_USERNAME
        - objectName: wallet_db_name
          key: WALLET_DB_NAME
        - objectName: wallet_db_password
          key: WALLET_DB_PASSWORD
        - objectName: wallet_db_username
          key: WALLET_DB_USERNAME
        - objectName: report_db_name
          key: REPORT_DB_NAME
        - objectName: report_db_password
          key: REPORT_DB_PASSWORD
        - objectName: report_db_username
          key: REPORT_DB_USERNAME
        - objectName: trustees_db_name
          key: TRUSTEES_DB_NAME
        - objectName: trustees_db_password
          key: TRUSTEES_DB_PASSWORD
        - objectName: trustees_db_username
          key: TRUSTEES_DB_USERNAME
