# apiVersion: v1
# kind: Secret
# metadata:
#   name: credentials
#   namespace: one-meristem-app
#   annotations:
#     kubernetes.io//service-account.name: app-spc-sa
#   type: kubernetes.io//service-account-token
# data:
#   key1: bHVnYXJkZXNvc2ExMDA=   # Github username
#   key2: Z2hwX3ZmMkdrb2ZTZWhuMm01UzJQQWR6RlFSRFZ3azNxNzQ2Tkdraw==    # Github Password
#   key3: VVhnQ2tiRDl5R0lMaGx0 # The Admin_Password
#   key4: cUhaT2pjSGRyS0xyYmhI     # Encryption key
#   key5: c210cC5tYWlsZXJzZW5kLm5ldA==     # Mailer_Host
#   key6: TVNfNG5iaGVZQHRlc3QtenhrNTR2OHpvbXFsank2di5tbHNlbmRlci5uZXQ=  # Mailer_Username
#   key7: bXNzcC5WQ2JLQlhDLjN6eGs1NHZ5cm96NGp5NnYucDVGb2V6ag==     # Mailer_Password
#   key8: MWtlcGYxS2xYYzlFVWpQU01jcUJ2UWY1RUlxTFduWHVFRXo1OFhiaU15ZkxRRURmT3BEbHRtTVJIRzg4TTN0bWNTQVJ1VzlHNmlNYzlFeFlNamZKd2ZJM01J #CREDIT_SWITCH_PUBLIC_KEY
#   key9: VU5sWWZBTlE1aGZwRWp1YVNJRmpYT1NLOTdOQVg2TkkwcFQyQUNwYTVhUElpMDRMYzNzd3BqOFh6c2N4SlpQcnpqVWIxWWQxRUZNNVo1eXA4VHg1SHdhSXM5 #CREDIT_SWITCH_PRIVATE_KEY
#   key10: QHdNSj1vdGxEMyhi #CREDIT_SWITCH_SMS_PASSWORD
#   key11: SFBVQU01REhBNzBXQ0NKR0ZOSzc= # HUAWEI_CLOUD_ACCESS_KEY_ID
#   key12: cnBJMHVwZjZubkhObkx6ZTRETGtYWG9mdWZWNzBFdXF3ZkpJSXVreA== # HUAWEI_CLOUD_SECRET_ACCESS_KEY
#   key13: cGx1bWJlcjEwMQ== # H2_PASSWORD
#   key14: cGtfc2FuZGJveF9WdW1jRjlEUk5QWGxPNlVMeHhTTk01Rng1TVMzNGFNQnp3bTJjMWUxQ0UyWHJYdm8= #PROVIDUS_API_PUBLIC_KEY
#   key15: c2tfc2FuZGJveF9Nb080S0pTWENYU1hZQno1M1djOWIzVzNrUjJ5N3d2MzBmMUd5Mzk5aDhPUTdnUDA= #PROVIDUS_API_SECRET_KEY



apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8sSecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: Opaque
data:
  key1: bHVnYXJkZXNvc2ExMDA=   # Github username
  key2: Z2hwXzFrSFJDVFJwdnBUY29VTGpicHJDSnZlNm03NkFKejNVNWsxTA==    # Github Password
  key3: VVhnQ2tiRDl5R0lMaGx0 # The Admin_Password
  key4: cUhaT2pjSGRyS0xyYmhI     # Encryption key
  key5: c210cC5tYWlsZXJzZW5kLm5ldA==     # Mailer_Host <-- Replace this with another secret
  key6: YXBp  # Mailer_Username
  key7: MWM1NTc1NjNjNTMzNzI2N2I5Y2FhMDMyYTVmZDdlNDg=    # Mailer_Password
  key8: MWtlcGYxS2xYYzlFVWpQU01jcUJ2UWY1RUlxTFduWHVFRXo1OFhiaU15ZkxRRURmT3BEbHRtTVJIRzg4TTN0bWNTQVJ1VzlHNmlNYzlFeFlNamZKd2ZJM01J #CREDIT_SWITCH_PUBLIC_KEY
  key9: VU5sWWZBTlE1aGZwRWp1YVNJRmpYT1NLOTdOQVg2TkkwcFQyQUNwYTVhUElpMDRMYzNzd3BqOFh6c2N4SlpQcnpqVWIxWWQxRUZNNVo1eXA4VHg1SHdhSXM5 #CREDIT_SWITCH_PRIVATE_KEY
  key10: QHdNSj1vdGxEMyhi #CREDIT_SWITCH_SMS_PASSWORD
  key11: SFBVQUVaSzNETExQTFZGWFpJQzU= # HUAWEI_CLOUD_ACCESS_KEY_ID
  key12: c05weTlSN0FjN0JIZU9VcDVhRGhyRERkY1lFYWh1M1BVQnNWM0s0NQ== # HUAWEI_CLOUD_SECRET_ACCESS_KEY
  key13: cGx1bWJlcjEwMQ== # H2_PASSWORD
  key14: cGtfc2FuZGJveF9WdW1jRjlEUk5QWGxPNlVMeHhTTk01Rng1TVMzNGFNQnp3bTJjMWUxQ0UyWHJYdm8= #PROVIDUS_API_PUBLIC_KEY
  key15: c2tfc2FuZGJveF9Nb080S0pTWENYU1hZQno1M1djOWIzVzNrUjJ5N3d2MzBmMUd5Mzk5aDhPUTdnUDA= #PROVIDUS_API_SECRET_KEY
  key16: c2VjcmV0 #TRUSTEES_CLIENT_SECRET


---

#OBS Access Secret
{{- if .Values.obsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.obsSecret.name }}
  namespace: {{ .Values.obsSecret.namespace }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
data:
  access.key: {{ .Values.obsSecret.data.accessKey }}
  secret.key: {{ .Values.obsSecret.data.secretKey }}
{{- end }}

#N.B - You can get these values yourself with:
# echo -n "<your_AK_here>" | base64
# echo -n "<your_SK_here>" | base64


