
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8sSecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: Opaque
data:
  #Web-App Credentials
  admin-password: {{ .Values.credentials.adminPassword | b64enc | quote }}
  encryption-key: {{ .Values.credentials.encryptionKey | b64enc | quote }}

  #Backend Credentials
  GITHUB_USERNAME:             {{ .Values.credentials.githubUsername | b64enc | quote }}
  GITHUB_PASSWORD:             {{ .Values.credentials.githubPassword | b64enc | quote }}
  ADMIN_PASSWORD:              {{ .Values.credentials.adminPassword | b64enc | quote }}
  ENCRYPTION_KEY:              {{ .Values.credentials.encryptionKey | b64enc | quote }}
  MAILER_HOST:                 {{ .Values.credentials.mailerHost | b64enc | quote }}
  MAILER_USERNAME:             {{ .Values.credentials.mailerUsername | b64enc | quote }}
  MAILER_PASSWORD:             {{ .Values.credentials.mailerPassword | b64enc | quote }}
  CREDIT_SWITCH_PUBLIC_KEY:    {{ .Values.credentials.creditSwitchPublicKey | b64enc | quote }}
  CREDIT_SWITCH_PRIVATE_KEY:   {{ .Values.credentials.creditSwitchPrivateKey | b64enc | quote }}
  CREDIT_SWITCH_SMS_PASSWORD:  {{ .Values.credentials.creditSwitchSmsPassword | b64enc | quote }}
  HUAWEI_CLOUD_ACCESS_KEY_ID:  {{ .Values.credentials.huaweiCloudAccessKeyId | b64enc | quote }}
  HUAWEI_CLOUD_SECRET_ACCESS_KEY: {{ .Values.credentials.huaweiCloudSecretAccessKey | b64enc | quote }}
  H2_PASSWORD:                 {{ .Values.credentials.h2Password | b64enc | quote }}
  PROVIDUS_API_PUBLIC_KEY:     {{ .Values.credentials.providusApiPublicKey | b64enc | quote }}
  PROVIDUS_API_SECRET_KEY:     {{ .Values.credentials.providusApiSecretKey | b64enc | quote }}
  TRUSTEES_CLIENT_SECRET:      {{ .Values.credentials.trusteesClientSecret | b64enc | quote }}
  ENC_SALT:                    {{ .Values.credentials.encSalt | b64enc | quote }}
  EXPO_TOKEN:                  {{ .Values.credentials.expoToken | b64enc | quote }}
  OKHI_HEADER_VALUE:           {{ .Values.credentials.okhiHeaderValue | b64enc | quote }}
  PAYSTACK_SECRET_KEY:         {{ .Values.credentials.paystackSecretKey | b64enc | quote }}
  SMILE_ID_PROD_API_KEY:   {{ .Values.credentials.smileIdProdApiKey | b64enc | quote }}
  SMILE_ID_DEV_API_KEY:    {{ .Values.credentials.smileIdDevApiKey | b64enc | quote }}
  MOBILE_SECRET:           {{ .Values.credentials.mobileSecret | b64enc | quote }}
  TRUSTEES_SECRET:         {{ .Values.credentials.trusteesSecret | b64enc | quote }}
  NOTIFICATION_SECRET:     {{ .Values.credentials.notificationSecret | b64enc | quote }}
  WEALTH_CLIENT_SECRET: {{ .Values.credentials.wealthClientSecret | b64enc | quote }}
  ID_HASHING_SECRET:    {{ .Values.credentials.idHashingSecret | b64enc | quote }}
  WEB_SECRET:           {{ .Values.credentials.webSecret | b64enc | quote }}
  WALLET_SECRET:        {{ .Values.credentials.walletSecret | b64enc | quote }}
  WEALTH_SECRET:        {{ .Values.credentials.wealthSecret | b64enc | quote }}
  MIDDLE_WARE_API_KEY:  {{ .Values.credentials.middlewareApiKey | b64enc | quote }}
  DOJAH_SECRET_KEY:     {{ .Values.credentials.dojahSecretKey | b64enc | quote }}
  DOJAH_PRIVATE_KEY:    {{ .Values.credentials.dojahPrivateKey | b64enc | quote }}
  PASTEL_API_KEY:       {{ .Values.credentials.pastelApiKey | b64enc | quote }}
  PASTEL_API_SECRET:    {{ .Values.credentials.pastelApiSecret | b64enc | quote }}

  
  # key1: bHVnYXJkZXNvc2ExMDA=   # Github username
  # key2: Z2hwXzFrSFJDVFJwdnBUY29VTGpicHJDSnZlNm03NkFKejNVNWsxTA==    # Github Password
  # key3: VVhnQ2tiRDl5R0lMaGx0 # The Admin_Password
  # key4: cUhaT2pjSGRyS0xyYmhI     # Encryption key
  # key5: c210cC5tYWlsZXJzZW5kLm5ldA==     # Mailer_Host <-- Replace this with another secret
  # key6: YXBp  # Mailer_Username
  # key7: MzRiODVjM2FjNzY2MGZhYTExZTJiM2IwOTk0YTFjOTY=    # Mailer_Password
  # key8: MWtlcGYxS2xYYzlFVWpQU01jcUJ2UWY1RUlxTFduWHVFRXo1OFhiaU15ZkxRRURmT3BEbHRtTVJIRzg4TTN0bWNTQVJ1VzlHNmlNYzlFeFlNamZKd2ZJM01J #CREDIT_SWITCH_PUBLIC_KEY
  # key9: VU5sWWZBTlE1aGZwRWp1YVNJRmpYT1NLOTdOQVg2TkkwcFQyQUNwYTVhUElpMDRMYzNzd3BqOFh6c2N4SlpQcnpqVWIxWWQxRUZNNVo1eXA4VHg1SHdhSXM5 #CREDIT_SWITCH_PRIVATE_KEY
  # key10: QHdNSj1vdGxEMyhi #CREDIT_SWITCH_SMS_PASSWORD
  # key11: SFBVQUVaSzNETExQTFZGWFpJQzU= # HUAWEI_CLOUD_ACCESS_KEY_ID
  # key12: c05weTlSN0FjN0JIZU9VcDVhRGhyRERkY1lFYWh1M1BVQnNWM0s0NQ== # HUAWEI_CLOUD_SECRET_ACCESS_KEY
  # key13: cGx1bWJlcjEwMQ== # H2_PASSWORD
  # key14: cGtfc2FuZGJveF9WdW1jRjlEUk5QWGxPNlVMeHhTTk01Rng1TVMzNGFNQnp3bTJjMWUxQ0UyWHJYdm8= #PROVIDUS_API_PUBLIC_KEY
  # key15: c2tfc2FuZGJveF9Nb080S0pTWENYU1hZQno1M1djOWIzVzNrUjJ5N3d2MzBmMUd5Mzk5aDhPUTdnUDA= #PROVIDUS_API_SECRET_KEY
  # key16: c2VjcmV0 #TRUSTEES_CLIENT_SECRET
  # key17: NWE3M2QzNzBlOWRjYzA4MDhlNWU5ZWFhY2Y2YWI1NDA=  #ENC_SALT
  # key18: TXY0R2JNZFlRQllJRFRhZ0NWTnc3TjBiY0FEWkFyZTVvOGJzQjFmcA==  #EXPO TOKEN
  # key19: MTgwOTQ1MDAtMTRlMy00OThhLWIxYWItOWM4NzQzOTJhOWI4 #OKHI_HEADER_VALUE
  # key20: c2tfdGVzdF9hOWFjMzcwMjY5YzRjZmNmYTZjNzk0MjZkMTgxODlkYzBkYmUxNjYx #PAYSTACK_SECRET_KEY
