# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: app-spc-sa
#   namespace: one-meristem-app
#   annotations:
#     cce.io/dew-resource: "[\"db-admin-secret-one-meristem-dev-env\",\"redis-credentials-one-meristem-dev-env\",\"kafka-credentials-one-meristem-dev-env\",\"db-notification_service-secret-one-meristem-dev-env\",\"db-users_service-secret-one-meristem-dev-env\",\"db-wallet_service-secret-one-meristem-dev-env\", \"db-report_service-secret-one-meristem-dev-env\"]"


apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cce.io/dew-resource: {{ .Values.serviceAccount.dewResources | toJson | quote }}



