{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.cloudGateway.tlsSecretName }}
  namespace: {{ .Values.global.namespace | default "one-meristem-app" }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.cloudGateway.tlsCert | quote }}
  tls.key: {{ .Values.ingress.cloudGateway.tlsKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.webApp.tlsSecretName }}
  namespace: {{ .Values.global.namespace | default "one-meristem-app" }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.webApp.tlsCert | quote }}
  tls.key: {{ .Values.ingress.webApp.tlsKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.adminApp.tlsSecretName }}
  namespace: {{ .Values.global.namespace | default "one-meristem-app" }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.adminApp.tlsCert | quote }}
  tls.key: {{ .Values.ingress.adminApp.tlsKey | quote }}
{{- end }}
