CREATE TABLE personal_savings
(
    id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                         TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                           VARCHAR(255)                            NOT NULL,
    last_modified_date                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_by                     VARCHAR(255)                            NOT NULL,
    version                              INTEGER                                          DEFAULT 0,
    status                               INTEGER                                          DEFAULT 1 NOT NULL,

    name                                 VARCHAR(255)                            NOT NULL,
    identifier                           VARCHAR(255)                            NOT NULL,
    description                          TEXT,

    interest_rate                        INTEGER                                 NOT NULL,
    tax                                  INTEGER                                 NOT NULL,
    fund_active_plan                     BOOLEAN                                 NOT NULL,
    locked_till_maturity                 BOOLEAN                                 NOT NULL,
    minimum_duration_days                INTEGER                                 NOT NULL,
    maximum_duration_days                INTEGER                                 NOT NULL,
    minimum_target_kobo                  BIGINT                                  NOT NULL,
    maximum_target_kobo                  BIGINT                                  NOT NULL,
    minimum_active_saving_funding_amount BIGINT                                  NOT NULL,
    maximum_active_saving_funding_amount BIGINT                                  NOT NULL,

    CONSTRAINT personal_savings_pkey PRIMARY KEY (id)
);

CREATE TABLE investment_products
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER                                          DEFAULT 0,
    status             INTEGER                                          DEFAULT 1 NOT NULL,


    name               VARCHAR(255)                            NOT NULL,
    uuid               VARCHAR(255)                            NOT NULL,
    slug               VARCHAR(255)                            NOT NULL,
    supported_currency VARCHAR(255)                            NOT NULL,
    description        TEXT,
    position           INTEGER                                 NOT NULL,
    is_active          BOOLEAN                                 NOT NULL DEFAULT FALSE,

    CONSTRAINT investment_products_pkey PRIMARY KEY (id)
);


CREATE TABLE investment_plans
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by            VARCHAR(255)                            NOT NULL,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_by      VARCHAR(255)                            NOT NULL,
    version               INTEGER                                          DEFAULT 0,
    status                INTEGER                                          DEFAULT 1 NOT NULL,


    investment_product_id BIGINT                                  NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    uuid                  VARCHAR(255)                            NOT NULL,
    slug                  VARCHAR(255)                            NOT NULL,
    core_product_id       VARCHAR(255)                            NOT NULL, -- TODO: REPLACE WITH ACTUAL VALUES FROM CORE WHEN THEY ARE CONFIGURED
    short_name            VARCHAR(255),
    description           TEXT,
    video_url             TEXT,
    position              INTEGER                                 NOT NULL,
    is_active             BOOLEAN                                 NOT NULL DEFAULT FALSE,

    CONSTRAINT investment_plans_pkey PRIMARY KEY (id),
    CONSTRAINT investment_plans_investment_product_id_fkey FOREIGN KEY (investment_product_id) REFERENCES investment_products (id)
);

CREATE TABLE investment_plan_settings
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,

    investment_plan_id          BIGINT NOT NULL UNIQUE,

    interest                    NUMERIC(10, 2),
    effective_yield             NUMERIC(10, 2),
    gross_yield                 NUMERIC(10, 2),
    processing_fee_percentage   NUMERIC(10, 2),

    interest_period             INTEGER,

    minimum_investment          BIGINT,
    minimum_tenure_days         INTEGER,
    maximum_tenure_days         INTEGER,

    rate_of_return              VARCHAR(200),
    tenor                       VARCHAR(200),
    offer_open_date             VARCHAR(200),
    offer_close_date            VARCHAR(200),
    investment_start_date       VARCHAR(200),
    investment_end_date         VARCHAR(200),
    investment_denomination     VARCHAR(50),
    risk_level                  VARCHAR(50),

    minimum_recurring_amount    BIGINT,

    returns_type                VARCHAR(100),
    compute_type                VARCHAR(50),

    bid                         NUMERIC(18, 4),
    offer                       NUMERIC(18, 4),

    minimum_units               NUMERIC(18, 4),
    minimum_recurring_units     NUMERIC(18, 4),

    can_withdraw_active         BOOLEAN DEFAULT FALSE,
    can_setup_recurring_debits  BOOLEAN DEFAULT FALSE,
    can_fund_active             BOOLEAN DEFAULT FALSE,

    penalty_on_early_withdrawal BOOLEAN DEFAULT FALSE,
    penalty_on_interest         BOOLEAN DEFAULT FALSE,
    penalty_percentage          NUMERIC(10, 2),

    fund_with_other_investments BOOLEAN,

    minimum_topup_amount        BIGINT,
    minimum_topup_units         NUMERIC(18, 4),
    CONSTRAINT investment_plan_settings_pkey PRIMARY KEY (id),
    CONSTRAINT fk_investment_plan_settings FOREIGN KEY (investment_plan_id) REFERENCES investment_plans (id) ON DELETE CASCADE
);

CREATE TABLE investment_plan_settings_images
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    investment_plan_id BIGINT       NOT NULL,
    image_url          VARCHAR(255) NOT NULL,
    CONSTRAINT investment_plan_settings_images_pkey PRIMARY KEY (id),
    CONSTRAINT fk_investment_plan_settings_images FOREIGN KEY (investment_plan_id) REFERENCES investment_plan_settings (id) ON DELETE CASCADE
);


CREATE UNIQUE INDEX personal_savings_identifier_uindex ON personal_savings (identifier);
CREATE UNIQUE INDEX investment_products_uuid_uindex ON investment_products (uuid);
CREATE UNIQUE INDEX investment_plans_uuid_uindex ON investment_plans (uuid);


INSERT INTO personal_savings (created_by, last_modified_by, name, identifier, description,
                              interest_rate, tax, fund_active_plan, locked_till_maturity, minimum_duration_days,
                              maximum_duration_days, minimum_target_kobo, maximum_target_kobo,
                              minimum_active_saving_funding_amount, maximum_active_saving_funding_amount)
VALUES ('SYSTEM', 'SYSTEM', 'Personal Target Savings', '3bae42c6-4479-4bf5-9e00-6feb8e506717', NULL, 17, 10, TRUE, TRUE,
        90, 1800,
        1000000, 50000000000, 50000, 500000000),
       ('SYSTEM', 'SYSTEM', 'Fixed Lock', '86342f61-abe6-4b47-980f-1341108d90c5', NULL, 17, 10, FALSE,
        TRUE, 90, 1800, 1000000, 50000000000, 50000, 500000000),
       ('SYSTEM', 'SYSTEM', 'Fixed Flexible', '1cc29759-6775-4162-9bd5-96c7cf8b370f', NULL, 13,
        10, TRUE, FALSE, 30, 1800, 1000000, 50000000000, 50000, 500000000);


DO
$$
    DECLARE
EquityId                    INTEGER;
        FixedDepositsId             INTEGER;
        DiscountedInvestmentId      INTEGER;
        MutualFundsId               INTEGER;
        EthicalEarningsId           INTEGER;
        RealEstateId                INTEGER;
        FixedTermDepositPortFolioId INTEGER;
        MoneyMarketFundId           INTEGER;
        FixedIncomeFundId           INTEGER;
        CommercialPaperId           INTEGER;
        EquityMarketFundId          INTEGER;
        TreasuryLinkedInvestmentId  INTEGER;
        EthicalEarningsPortfolioId  INTEGER;
        MeristemDollarFundId        INTEGER;
        MeristemDollarInvestmentId  INTEGER;
BEGIN


INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Equity', '0b81bfba-f33a-47ae-b538-52b8cc46ad84', 'equity', 'NGN',
        'Invest in equities', 6,
        false)
    RETURNING id INTO EquityId;

INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Fixed Deposits', 'b668dd79-b24e-43f2-8d73-bd085cca2cf4', 'fixed-deposits', 'NGN',
        'Secure your funds with a guaranteed return over a fixed period', 4, true)
    RETURNING id INTO FixedDepositsId;

INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Discounted Investment',
        'a6123bf3-b229-4094-a0fb-c4dc7543a99c', 'discounted-investment', 'NGN',
        'Maximize your earnings by investing in discounted financial instruments', 2, true)
    RETURNING id INTO DiscountedInvestmentId;

INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Mutual Funds',
        'c12fd583-e88a-48fc-bab7-71f2cf1f56d7', 'mutual-funds', 'NGN',
        'Diversify your portfolio with professionally managed investment funds', 3, true)
    RETURNING id INTO MutualFundsId;

INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Ethical Earnings',
        'ed97db69-2558-4eb2-b4b0-ded42d0b2a4e', 'ethical-earnings', 'NGN',
        'Invest in socially responsible and Shariah-compliant opportunities', 5, true)
    RETURNING id INTO EthicalEarningsId;

INSERT INTO investment_products (created_by, last_modified_by, name, uuid, slug, supported_currency,
                                 description, position, is_active)
VALUES ('SYSTEM', 'SYSTEM', 'Real Estate',
        'e10d55c9-7510-4041-b3da-adebbb511d4a', 'real-estate', 'NGN', 'Realestate investment oppoturnities', 7,
        true)
    RETURNING id INTO RealEstateId;


INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('FIVP', 'SYSTEM', 'SYSTEM', FixedDepositsId, 'Fixed Term Investment Portfolio',
        'e39c16aa-96b3-4c2e-8984-9a0c66b36b9f', 'fixed-term-investment-portfolio', 'FIX-TIP', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749582076/wb2videos/iywahqyubziwshkeeluz.mp4', 1,
        true)
    RETURNING id INTO FixedTermDepositPortFolioId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('', 'SYSTEM', 'SYSTEM', MutualFundsId, 'Money Market Fund',
        '4df9e110-2b01-4078-869b-d76e0d61714d', 'meristem-money-market-fund', 'MMMF', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749630618/wb2videos/MONEY_MARKET_FUND_wzfhcu.mp4',
        1,
        true)
    RETURNING id INTO MoneyMarketFundId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('','SYSTEM', 'SYSTEM', MutualFundsId, 'Fixed Income Fund',
        '99255092-bdf9-4fe8-8b1b-9177abb3fdf3', 'meristem-fixed-income-fund', 'MFIF', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749630687/wb2videos/MFIF_cay6o7.mp4', 3, true)
    RETURNING id INTO FixedIncomeFundId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('','SYSTEM', 'SYSTEM', DiscountedInvestmentId, 'Commercial Paper',
        '5a77240f-3050-448a-ac46-174d030b08b3', 'commercial-paper', 'CP', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749630549/wb2videos/COMMERCIAL_PAPERS_bjkjir.mp4',
        1,
        true)
    RETURNING id INTO CommercialPaperId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('','SYSTEM', 'SYSTEM', MutualFundsId, 'Equity Market Fund',
        '7f142d21-d19a-4844-9b41-6ecb6704b4ee', 'meristem-equity-market-fund', 'MEMF', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749630649/wb2videos/MEMF_vqijvz.mp4', 2, true)
    RETURNING id INTO EquityMarketFundId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('TLIP', 'SYSTEM', 'SYSTEM', DiscountedInvestmentId, 'Treasury Linked Investment',
        'c3158068-ee82-4052-a0ac-44fe50455eda', 'treasury-linked-investment', 'T-Bills', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749582074/wb2videos/zomkmi7g6y9yl0hazzw8.mp4', 2,
        true)
    RETURNING id INTO TreasuryLinkedInvestmentId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('EEP', 'SYSTEM', 'SYSTEM', EthicalEarningsId, 'Ethical Earnings Portfolio',
        'fced68f5-dd06-4c2f-9ea6-598f24f1e5a9',
        'meristem-ethical-earnings-portfolio', NULL, NULL, NULL, 1, true)
    RETURNING id INTO EthicalEarningsPortfolioId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('','SYSTEM', 'SYSTEM', MutualFundsId, 'Meristem Dollar Mutual Fund',
        '45dede92-2405-4811-9724-45e4638e742f', 'meristem-dollar-fund', 'MDMF', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749630618/wb2videos/MONEY_MARKET_FUND_wzfhcu.mp4',
        3,
        true)
    RETURNING id INTO MeristemDollarFundId;

INSERT INTO investment_plans (core_product_id, created_by, last_modified_by, investment_product_id,
                              name, uuid, slug, short_name, description, video_url, position, is_active)
VALUES ('','SYSTEM', 'SYSTEM', FixedDepositsId, 'Meristem-Dollar Investment Portfolio',
        'e45f42bb-89f0-4ed5-a87a-fdaa49684cca', 'meristem-dollar-investment-portfolio', 'MDIP', NULL,
        'https://res.cloudinary.com/dptx3beqe/video/upload/v1749582076/wb2videos/iywahqyubziwshkeeluz.mp4', 1,
        false)
    RETURNING id INTO MeristemDollarInvestmentId;


INSERT INTO investment_plan_settings (investment_plan_id, interest, effective_yield, gross_yield,
                                      processing_fee_percentage,
                                      interest_period, minimum_investment, minimum_tenure_days,
                                      maximum_tenure_days,
                                      rate_of_return, investment_denomination, risk_level,
                                      minimum_recurring_amount,
                                      returns_type, compute_type, bid, offer, minimum_units,
                                      minimum_recurring_units,
                                      can_withdraw_active, can_setup_recurring_debits, can_fund_active,
                                      penalty_on_early_withdrawal, penalty_on_interest, penalty_percentage,
                                      fund_with_other_investments, minimum_topup_amount, minimum_topup_units)
VALUES (FixedTermDepositPortFolioId, 20, NULL, NULL, 0,
        NULL, 20000000, 30, 365,
        '10.75% - 16.39%', 'Naira', 'Low', 100000,
        'End of tenor', 'percentage', NULL, NULL, NULL, NULL,
        TRUE, TRUE, FALSE,
        TRUE, TRUE, 20,
        NULL, NULL, NULL),


       (MoneyMarketFundId, NULL, 20.41, 21.99, 0,
        NULL, 1000000, 30, 365,
        NULL, 'Naira', 'Low', 100000,
        'Quarterly', 'percentage', NULL, NULL, NULL, NULL,
        TRUE, TRUE, TRUE,
        NULL, NULL, NULL,
        NULL, 100000, NULL),

       (FixedIncomeFundId, NULL, NULL, NULL, 0,
        NULL, NULL, 90, NULL,
        NULL, 'Naira', 'Medium', NULL,
        'Price Appreciation/Bi-Annual dividends', 'bid-offer', 130.02, 110.02, 100, 10,
        TRUE, TRUE, TRUE,
        NULL, NULL, NULL,
        NULL, NULL, 50),

       (CommercialPaperId, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL,
        NULL, NULL, 'Medium', NULL,
        'End of tenor', NULL, NULL, NULL, NULL, NULL,
        FALSE, NULL, FALSE,
        NULL, NULL, NULL,
        NULL, NULL, NULL),

       (EquityMarketFundId, NULL, NULL, NULL, 0,
        NULL, NULL, 30, NULL,
        NULL, 'Naira', 'Medium', NULL,
        'Price Appreciation/Annual dividends', 'bid-offer', 90.9032, 50.4423, 1000, 10,
        TRUE, TRUE, TRUE,
        NULL, NULL, NULL,
        NULL, NULL, 10),

       (TreasuryLinkedInvestmentId, NULL, NULL, NULL, 0.25,
        NULL, 100000000, 91, 364,
        'Mirrors return on FGN Treasury Bills', 'Naira', 'Low', NULL,
        'End of tenor', NULL, NULL, NULL, NULL, NULL,
        FALSE, NULL, FALSE,
        TRUE, TRUE, NULL,
        TRUE, NULL, NULL),

       (EthicalEarningsPortfolioId, 7, NULL, NULL, 0,
        NULL, 100000, 182, NULL,
        '8% per anum', 'Naira', 'Low', 10000000,
        'Bi-annual (April & October)', 'percentage', NULL, NULL, NULL, NULL,
        FALSE, TRUE, TRUE,
        TRUE, TRUE, 40,
        NULL, 10000000, NULL),

       (MeristemDollarFundId, NULL, NULL, NULL, 0,
        NULL, NULL, 180, NULL,
        NULL, 'USD', 'Medium', NULL,
        'Price Appreciation', 'bid-offer', 29.4957, 29.6522, 50, 10,
        TRUE, TRUE, TRUE,
        NULL, NULL, NULL,
        NULL, NULL, 10),

       (MeristemDollarInvestmentId, NULL, NULL, NULL, 0,
        NULL, 200000, 90, 365,
        '3.5% - 5%', 'USD', 'Low', 50000,
        'End of tenor', 'percentage', NULL, NULL, NULL, NULL,
        FALSE, FALSE, TRUE,
        TRUE, TRUE, 25,
        NULL, NULL, NULL);

END
$$;

