CREATE TABLE transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    wallet_id                 BIGINT                                  NOT NULL,
    virtual_account_id        BIGINT,
    reference                 VARCHAR(50)                             NOT NULL,
    amount                    DECIMAL(14, 4)                          NOT NULL,
    previous_balance          DECIMAL(14, 4),
    new_balance               DECIMAL(14, 4),
    type                      VARCHAR(50)                             NOT NULL,
    method                    VARCHAR(50)                             NOT NULL,
    narration                 VARCHAR(255),
    provider_reference        VARCHAR(50)                             NOT NULL,
    senders_bank_name         VARCHAR(100),
    senders_name              VARCHAR(100),
    senders_bank_code         VARCHAR(20),
    senders_account_number    VARCHAR(20),
    account_name              VARCHAR(100),
    account_number            VARCHAR(20),
    transaction_date          TIMESTAMP                               NOT NULL,
    transaction_status        INTEGER                                 NOT NULL,
    provider_transaction_date TIMESTAMP                               NOT NULL,


    CONSTRAINT "pk_transactions" PRIMARY KEY (id)
);


CREATE TABLE transactions_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    transaction_id     BIGINT                                  NOT NULL,
    map_key            VARCHAR(100)                            NOT NULL,
    map_value          VARCHAR(300)                            NOT NULL,

    CONSTRAINT "pk_transactions_metadata" PRIMARY KEY (id)
);





CREATE TABLE activity_log
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    activity_date        TIMESTAMP     NOT NULL,
    actor              VARCHAR(255) NOT NULL,
    action             VARCHAR(255) NOT NULL,
    entity             VARCHAR(255) NOT NULL,
    entity_id          BIGINT,
    application        VARCHAR(255) NOT NULL,
    activity           TEXT         NOT NULL,

    CONSTRAINT "pk_activity_log" PRIMARY KEY (id)
);

CREATE TABLE activity_log_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER                                          DEFAULT 1 NOT NULL,

    map_key            VARCHAR(255)       NOT NULL,
    map_value          TEXT       NOT NULL,
    activity_log_id    BIGINT       NOT NULL,
    CONSTRAINT "pk_activity_log_metadata" PRIMARY KEY (id),
    CONSTRAINT fk_activity_log
        FOREIGN KEY (activity_log_id) REFERENCES activity_log (id) ON DELETE CASCADE
);

-- Helpful indexes
CREATE INDEX idx_activity_log_entity_app
    ON activity_log (entity, application);

CREATE INDEX idx_activity_log_timestamp
    ON activity_log (activity_date);

CREATE UNIQUE INDEX IDX_TRANSACTIONS_REFERENCE ON transactions (reference);
CREATE INDEX IDX_TRANSACTIONS_WALLET_ID ON transactions (wallet_id);
CREATE INDEX IDX_TRANSACTIONS_VA_ID ON transactions (virtual_account_id);
CREATE INDEX IDX_TRANSACTIONS_AN_ID ON transactions (account_number);
CREATE INDEX IDX_TRANSACTIONS_TYPE_ID ON transactions (type);
CREATE INDEX IDX_TRANSACTIONS_METHOD_ID ON transactions (method);
CREATE UNIQUE INDEX IDX_TRANSACTIONS_PR_ID ON transactions (provider_reference);