# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cloud-gateway
#   namespace: one-meristem-app
#   labels:
#     app: cloud-gateway
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: cloud-gateway
#   template:
#     metadata:
#       labels:
#         app: cloud-gateway
#     spec:
#       serviceAccountName: one-meristem-app
#       containers:
#       - name: cloud-gateway
#         image: swr.cn-south-1.myhuaweicloud.com/one-meristem/cloud-gateway # Replace with your actual container image
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 20010
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: "default"
#         - name: SPRING_PROFILES_ACTIVE
#           value: "default"
#         - name: GITHUB_BRANCH 
#           value: "wallet"
#         - name: APP_PROFILE
#           value: "local"
#         - name: SERVER_PORT
#           value: "20010"
#         - name: COMPANY_NAME
#           value: "Meristem Securities Limited"
#         - name: DATA_PRIVACY_POLICY_URL
#           value: https://www.onemerristem.merristem.com
#         - name: GREEN_LOGO_URL
#           value: https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Green_Logo.png
#         - name: WHITE_LOGO_URL
#           value: https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_White_Logo.png
#         - name: FINANCE_LOGO_URL
#           value: https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Finance_Logo.png
#         - name: CONFIG_SERVER_URL
#           value: "http://config-server:20000/config"
#         - name: USER_SERVICE_URI
#           value: "http://users-service:20020"
#         - name: NOTIFICATION_SERVICE_URI
#           value: "http://notification-service:20030"
#         - name: WALLET_SERVICE_URI
#           value: "http://wallet-service:20040"
#         - name: REPORT_SERVICE_URI
#           value: "http://report-service:20050"
#         - name: ADMIN_USERNAME
#           value: "admin"  # Replace with your actual admin username
#         - name: ADMIN_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: credentials
#               key: key3  # The key in the secret that contains the admin password
#         - name: ENCRYPTION_KEY
#           valueFrom: 
#             secretKeyRef:
#               name: credentials
#               key: key4
#         - name: REDIS_HOST
#           valueFrom: 
#             secretKeyRef:
#               name: huawei-csms-credentials
#               key: REDIS_HOST
#         - name: REDIS_PASSWORD
#           valueFrom: 
#             secretKeyRef:
#               name: huawei-csms-credentials
#               key: REDIS_PASSWORD
#         - name: H2_PASSWORD
#           valueFrom: 
#             secretKeyRef:
#               name: credentials
#               key: key13
#         volumeMounts:
#         - name: huawei-csms-credentials
#           mountPath: /mnt/secrets-store
#         - name: pv-evs
#           mountPath: /data
#           readOnly: true
#         resources:
#           limits:
#             cpu: "1"
#             memory: 1Gi
#           requests:
#             cpu: "0.5"
#             memory: 512Mi
#       imagePullSecrets:
#       - name: default-secret  # Replace with your image pull secret if using private registry
#       volumes:
#       - name: pv-evs
#         persistentVolumeClaim:
#           claimName: cloud-gateway-pvc-evs
#       - name: huawei-csms-credentials
#         csi:
#           driver: secrets-store.csi.k8s.io
#           readOnly: true
#           volumeAttributes:
#             secretProviderClass: huawei-csms-credentials # Name of the SecretProviderClass created in the previous step
#             csi.storage.k8s.io/provisioner-secret-name: huawei-csms-credentials
#             csi.storage.k8s.io/provisioner-secret-namespace: one-meristem-app
#             #csi.storage.k8s.io/node-publish-secret-name: huawei-csms-credentials
#             #csi.storage.k8s.io/node-publish-secret-namespace: one-meristem-app
            

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-gateway.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "cloud-gateway.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-gateway.name" . }}
  #The Rolling Update strategy is used to ensure zero downtime during updates.
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-gateway.name" . }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName | default "app-spc-sa" }}
      containers:
        - name: {{ include "cloud-gateway.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          # HEALTH CHECKS START HERE
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 90
            periodSeconds: 35
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
          volumeMounts:
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else }}
            {}
            {{- end }}
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
