# apiVersion: v1
# kind: Service
# metadata:
#   name: cloud-gateway
#   namespace: one-meristem-app
#   annotations:
#     kubernetes.io/elb.class: performance  # Matches the Ingress ELB type
#     kubernetes.io/elb.protocol-port: "https:443" # Protocol and port mapping
#     kubernetes.io/elb.lb-algorithm: ROUND_ROBIN  # Default load balancing algorithm
#     kubernetes.io/elb.health-check-flag: "on"  # Enable health checks
#     kubernetes.io/elb.health-check-option: '{"protocol":"HTTPS”,”port”:”443”,”uri":"/health","interval":5,"timeout":10,"rise":2,"fall":2}'  # Health check configuration
#   labels:
#     app: cloud-gateway
# spec:
#   selector:
#     app: cloud-gateway
#   ports:
#     - name: https
#       protocol: TCP
#       port: 443
#       targetPort: 20010
#   type: ClusterIP


apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-gateway.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "cloud-gateway.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    app: {{ include "cloud-gateway.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}