CREATE TABLE permissions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE onboardingRequirements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    display_name       VARCHAR(50)                             NOT NULL,
    requirement_name   VARCHAR(50)                             NOT NULL,
    mandatory          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_requirements PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_permissions
(
    roles_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

CREATE TABLE user_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    id_type            VARCHAR(50)                             NOT NULL,
    additional_url     VARCHAR(1000)                           NOT NULL,
    id_card_front_url  VARCHAR(1000)                           NOT NULL,
    id_card_back_url   VARCHAR(1000)                           NOT NULL,
    selfie_image_url   VARCHAR(1000)                           NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_document PRIMARY KEY (id)
);

CREATE TABLE user_onboarding
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    completed          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_onboarding PRIMARY KEY (id)
);

CREATE TABLE user_profile
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    avatar_url        VARCHAR(500),
    pin               VARCHAR(200),
    date_of_birth     DATE,
    gender            VARCHAR(20),
    referral_code        VARCHAR(15)                            NOT NULL,
    onboarding_completed BOOLEAN DEFAULT FALSE                  NOT NULL,
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status             INT DEFAULT 1                           NOT NULL,
    email                VARCHAR(200)                            NOT NULL,
    first_name           VARCHAR(150)                            NOT NULL,
    last_name            VARCHAR(150)                            NOT NULL,
    middle_name          VARCHAR(150),
    password             VARCHAR(200)                            NOT NULL,
    phone_number         VARCHAR(50)                             NOT NULL,
    password_attempt     INT DEFAULT 0                           NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE next_of_kin
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status               INT DEFAULT 1                           NOT NULL,
    email                VARCHAR(200)                            NOT NULL,
    full_name           VARCHAR(150)                            NOT NULL,
    phone_number         VARCHAR(50)                             NOT NULL,
    user_id            BIGINT                                   NOT NULL,
    relationship        VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_next_of_kin PRIMARY KEY (id)
);


CREATE TABLE id_card
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status               INT DEFAULT 1                           NOT NULL,
    id_card_type         VARCHAR(30)                             NOT NULL,
    id_value             VARCHAR(30)                             NOT NULL,
    issued_date          DATE                                    NOT NULL,
    expiry_date          DATE,
    user_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_id_card PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (users_id, roles_id)
);

CREATE TABLE otp_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    code               INT                                     NOT NULL,
    user_id            VARCHAR(200)                            NOT NULL,
    otp_type           INT                                     NOT NULL,
    verified           BOOLEAN DEFAULT FALSE                   NOT NULL,
    expires_at         TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_otpverification PRIMARY KEY (id)
);


CREATE TABLE address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    house_address VARCHAR(150)                            NOT NULL,
    city          VARCHAR(100)                            NOT NULL,
    landmark      VARCHAR(100)                             NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    approved             INT DEFAULT 0                           NOT NULL,
    processing             INT DEFAULT 0                           NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE avatars
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    url                VARCHAR(500)                            NOT NULL,
    CONSTRAINT pk_avatars PRIMARY KEY (id)
);

CREATE TABLE oauth2_registered_client (
                                          id varchar(100) NOT NULL,
                                          client_id varchar(100) NOT NULL,
                                          client_id_issued_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                          client_secret varchar(200) DEFAULT NULL,
                                          client_secret_expires_at timestamp DEFAULT NULL,
                                          client_name varchar(200) NOT NULL,
                                          client_authentication_methods varchar(1000) NOT NULL,
                                          authorization_grant_types varchar(1000) NOT NULL,
                                          redirect_uris varchar(1000) DEFAULT NULL,
                                          post_logout_redirect_uris varchar(1000) DEFAULT NULL,
                                          scopes varchar(1000) NOT NULL,
                                          client_settings varchar(2000) NOT NULL,
                                          token_settings varchar(2000) NOT NULL,
                                          PRIMARY KEY (id)
);


CREATE TABLE oauth2_authorization (
                                      id varchar(100) NOT NULL,
                                      registered_client_id varchar(100) NOT NULL,
                                      principal_name varchar(200) NOT NULL,
                                      authorization_grant_type varchar(100) NOT NULL,
                                      authorized_scopes varchar(1000) DEFAULT NULL,
                                      attributes text DEFAULT NULL,
                                      state varchar(500) DEFAULT NULL,
                                      authorization_code_value text DEFAULT NULL,
                                      authorization_code_issued_at timestamp DEFAULT NULL,
                                      authorization_code_expires_at timestamp DEFAULT NULL,
                                      authorization_code_metadata text DEFAULT NULL,
                                      access_token_value text DEFAULT NULL,
                                      access_token_issued_at timestamp DEFAULT NULL,
                                      access_token_expires_at timestamp DEFAULT NULL,
                                      access_token_metadata text DEFAULT NULL,
                                      access_token_type varchar(100) DEFAULT NULL,
                                      access_token_scopes varchar(1000) DEFAULT NULL,
                                      oidc_id_token_value text DEFAULT NULL,
                                      oidc_id_token_issued_at timestamp DEFAULT NULL,
                                      oidc_id_token_expires_at timestamp DEFAULT NULL,
                                      oidc_id_token_metadata text DEFAULT NULL,
                                      refresh_token_value text DEFAULT NULL,
                                      refresh_token_issued_at timestamp DEFAULT NULL,
                                      refresh_token_expires_at timestamp DEFAULT NULL,
                                      refresh_token_metadata text DEFAULT NULL,
                                      user_code_value text DEFAULT NULL,
                                      user_code_issued_at timestamp DEFAULT NULL,
                                      user_code_expires_at timestamp DEFAULT NULL,
                                      user_code_metadata text DEFAULT NULL,
                                      device_code_value text DEFAULT NULL,
                                      device_code_issued_at timestamp DEFAULT NULL,
                                      device_code_expires_at timestamp DEFAULT NULL,
                                      device_code_metadata text DEFAULT NULL,
                                      PRIMARY KEY (id)
);


CREATE TABLE smile_id_record
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    job_id             VARCHAR(100)                            NOT NULL,
    user_id            VARCHAR(150)                            NOT NULL,
    message            VARCHAR(300),
    timestamp          VARCHAR(40)                             NOT NULL,
    job_type           INTEGER                                 NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_smile_id_record PRIMARY KEY (id)
);

ALTER TABLE smile_id_record
    ADD CONSTRAINT fk_smileid_onrequirements FOREIGN KEY (requirement_id) REFERENCES onboardingRequirements(id);

ALTER TABLE smile_id_record
    ADD CONSTRAINT uc_smile_id_record_job UNIQUE (job_id);

CREATE INDEX idx_smileidrecord_job_id ON smile_id_record (job_id, user_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE address
    ADD CONSTRAINT uc_address_user UNIQUE (user_id);

ALTER TABLE otp_verification
    ADD CONSTRAINT uc_otpver_code_uid_ot UNIQUE (code, user_id, otp_type);

CREATE INDEX idx_otpver_uid_ot ON otp_verification (user_id, otp_type);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_referral_code UNIQUE (referral_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

CREATE INDEX idx_users_email ON users (email);

CREATE UNIQUE INDEX idx_onbaording_user_requirement_id ON user_onboarding(user_id, requirement_id);

CREATE INDEX idx_oauth2_registered_client_client_id ON oauth2_registered_client(client_id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES onboardingRequirements (id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES onboardingRequirements (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permissions_id) REFERENCES permissions (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

CREATE INDEX idx_roles_permissions_permissions_id ON roles_permissions(permissions_id);

CREATE INDEX idx_roles_permissions_roles_id ON roles_permissions(roles_id);

CREATE INDEX idx_users_roles_user_id ON users_roles(users_id);

CREATE INDEX idx_users_roles_roles_id ON users_roles(roles_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_users FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE next_of_kin
    ADD CONSTRAINT fk_user_on_next_of_kin FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE id_card
    ADD CONSTRAINT  fk_user_on_id_card FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO onboardingRequirements (
    created_date, created_by, last_modified_date, last_modified_by, version, status,
    display_name, requirement_name, mandatory
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'BVN Verification', 'BVN', TRUE),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'Address Verification', 'PROOF_OF_ADDRESS', TRUE),
    -- IF NIN IS PROVIDED, OTHER GOVERNMENT ISSUED ID IS NOT REQUIRED
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'ID Verification', 'GOVERNMENT_ISSUED_ID', FAlSE),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'ID Verification', 'NIN', TRUE);


DO $$
    DECLARE
        UsersId integer;

        RolesAdminID integer;
        RolesSuperAdminID integer;
        RolesUserID integer;

        UsersGetID integer;
        UsersChangePasswordID integer;
        UsersOnboardOnboardID integer;
        UsersOnboardGetID integer;
        UsersNextOfKinCreateID integer;
        UsersGetSmileIdTokenID integer;
        AdminApproveAddressID integer;
        AdminNextOfKinUpdateID integer;
        AdminOnboardProcessAddressID integer; -- TODO: SWITCH TO OKHI AND DELETE
        AdminOnboardApproveAddressID integer; -- TODO: SWITCH TO OKHI AND DELETE
        AdminChangePasswordID integer;
        UsersChangeAvatarID integer;
        UsersChangePinID integer;
        UsersPhoneNumberUpdateID integer;
        SuperAdminAdminCreateID integer;
BEGIN

    -- USERS
    INSERT INTO users (created_date, created_by, last_modified_date, last_modified_by, version, email, first_name, last_name, middle_name, password, phone_number)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'oneappsuperadmin@meristemng.com', 'Super', 'Admin', '', '$2a$12$zoqPU9DmUuSysmmH47ic.OHx3tXVHf5lJDUDNtpJjC3FM5tUcVd3W', '') RETURNING id INTO UsersId;

    -- ROLES
    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'ADMIN') RETURNING id INTO RolesAdminID;

    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'SUPER_ADMIN') RETURNING id INTO RolesSuperAdminID;

    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'USER') RETURNING id INTO RolesUserID;

    -- PERMISSIONS
    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get') RETURNING id INTO UsersGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change-password') RETURNING id INTO UsersChangePasswordID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.onboard.onboard') RETURNING id INTO UsersOnboardOnboardID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.onboard.get') RETURNING id INTO UsersOnboardGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.next_of_kin.create') RETURNING id INTO UsersNextOfKinCreateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get_smile_id_token') RETURNING id INTO UsersGetSmileIdTokenID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.next_of_kin.update') RETURNING id INTO AdminNextOfKinUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.onboard.approve_address') RETURNING id INTO AdminOnboardApproveAddressID; -- TODO: SWITCH TO OKHI AND DELETE

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.onboard.process_address') RETURNING id INTO AdminOnboardProcessAddressID; -- TODO: SWITCH TO OKHI AND DELETE

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.phone-number.update') RETURNING id INTO UsersPhoneNumberUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.change.password') RETURNING id INTO AdminChangePasswordID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change.avatar') RETURNING id INTO UsersChangeAvatarID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change.pin') RETURNING id INTO UsersChangePinID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'super_admin.admin.create') RETURNING id INTO SuperAdminAdminCreateID;

    -- USERS_ROLES
    INSERT INTO users_roles VALUES (UsersId, RolesSuperAdminID);

    -- ROLES_PERMISSIONS
    INSERT INTO roles_permissions (roles_id, permissions_id)
    VALUES (RolesUserID, UsersGetID),
           (RolesUserID, UsersChangePasswordID),
           (RolesUserID, UsersOnboardOnboardID),
           (RolesUserID, UsersOnboardGetID),
           (RolesUserID, UsersNextOfKinCreateID),
           (RolesUserID, UsersGetSmileIdTokenID),
           (RolesAdminID, AdminNextOfKinUpdateID),
           (RolesAdminID, AdminOnboardProcessAddressID), -- TODO: SWITCH TO OKHI AND DELETE
           (RolesAdminID, AdminOnboardApproveAddressID), -- TODO: SWITCH TO OKHI AND DELETE
           (RolesAdminID, AdminChangePasswordID),
           (RolesUserID, UsersChangeAvatarID),
           (RolesUserID, UsersChangePinID),
           (RolesUserID, UsersPhoneNumberUpdateID),
           (RolesSuperAdminID, SuperAdminAdminCreateID);

END $$;

INSERT INTO oauth2_registered_client
VALUES
    ('b4c1e3f7-7238-4453-a68e-8a52faf61834', 'mobile-service', NOW(), '$2a$10$BayFPa39DOsXHezSVcWIrONwom81s46vDs6js4AK1fx/hRR37Rx7S', NULL, 'Mobile Service', 'client_secret_post,client_secret_basic', 'refresh_token,password,client_credentials', '', '', 'user.read,user.write,profile,send_otp,verify_otp,create_user,users.get,password_reset', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":false,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",57600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}'),
    ('38463a9b-55ef-4df0-a319-63f5c60475d8', 'users-service', NOW(), '$2a$10$I0HYSs94VokxDXX77ubhsudZSrz96lyfOTLetGwyTHotmJo6cX9YS', NULL, 'Users Service', 'client_secret_post,client_secret_basic', 'refresh_token,client_credentials', '', '', '', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}'),
    ('8705d10f-81b1-4095-9424-955b03e47d4a', 'notification-service', NOW(), '$2a$10$T929snsP.zmaysL7Byji1.6Y2yOvkFWniUcGl0Cb3dt3HWdXLb83a', NULL, 'Notification Service', 'client_secret_post,client_secret_basic', 'refresh_token,client_credentials', '', '', '', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');
