CREATE TABLE permissions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE beneficiaries
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date             TIMESTAMP                               NOT NULL,
    created_by               VARCHAR(255)                            NOT NULL,
    last_modified_date       TIMESTAMP,
    last_modified_by         VARCHAR(255)                            NOT NULL,
    version                  INT,
    status                   INT DEFAULT 1                           NOT NULL,

    owner_id                 BIGINT                                  NOT NULL,
    first_name               VARCHAR(100)                            NOT NULL,
    last_name                VARCHAR(100)                            NOT NULL,
    beneficiary_relationship VARCHAR(50)                             NOT NULL,
    gender                   VARCHAR(30)                             NOT NULL,
    email                    VARCHAR(300)                            NOT NULL,
    phone_number             VARCHAR(20)                             NOT NULL,
    dob                      DATE                                    NOT NULL,
    address                  TEXT                                    NOT NULL,
    marital_status           VARCHAR(20)                             NOT NULL,
    bank_name                VARCHAR(100)                            NOT NULL,
    account_number           VARCHAR(20)                             NOT NULL
);

CREATE TABLE requirements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    display_name       VARCHAR(50)                             NOT NULL,
    requirement_name   VARCHAR(50)                             NOT NULL,
    mandatory          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_requirements PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_permissions
(
    roles_id       BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

CREATE TABLE user_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    id_type            VARCHAR(50)                             NOT NULL,
    additional_url     VARCHAR(2000)                           NOT NULL,
    id_card_front_url  VARCHAR(2000),
    id_card_back_url   VARCHAR(2000),
    selfie_image_url   VARCHAR(2000),
    requirement_id     BIGINT                                  NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_document PRIMARY KEY (id)
);

CREATE TABLE user_onboarding
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    completed          BOOLEAN                                 NOT NULL,
    type               INT                                     NOT NULL,
    CONSTRAINT pk_user_onboarding PRIMARY KEY (id)
);

CREATE TABLE user_profile
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status               INT     DEFAULT 1                       NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    image_key           VARCHAR(500),
    pin                  VARCHAR(200),
    date_of_birth        DATE,
    gender               VARCHAR(20),
    state_of_origin      VARCHAR(200),
    country_of_origin    VARCHAR(200),
    lg_of_origin         VARCHAR(200),
    marital_status       VARCHAR(50),
    referral_code        VARCHAR(15)                             NOT NULL,
    onboarding_completed BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status             INT DEFAULT 1                           NOT NULL,
    email                VARCHAR(200)                            NOT NULL,
    first_name           VARCHAR(150)                            NOT NULL,
    last_name            VARCHAR(150)                            NOT NULL,
    middle_name          VARCHAR(150),
    password             VARCHAR(200)                            NOT NULL,
    phone_number         VARCHAR(50)                             NOT NULL,
    password_attempt     INT DEFAULT 0                           NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE next_of_kin
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status               INT DEFAULT 1                           NOT NULL,
    email                VARCHAR(200)                            NOT NULL,
    full_name           VARCHAR(150)                            NOT NULL,
    phone_number         VARCHAR(50)                             NOT NULL,
    user_id            BIGINT                                   NOT NULL,
    relationship        VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_next_of_kin PRIMARY KEY (id)
);


CREATE TABLE id_card
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP                               NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    last_modified_date   TIMESTAMP,
    last_modified_by     VARCHAR(255)                            NOT NULL,
    version              INT,
    status               INT DEFAULT 1                           NOT NULL,
    id_card_type         VARCHAR(30)                             NOT NULL,
    id_value             VARCHAR(30)                             NOT NULL,
    issued_date          VARCHAR(20),
    expiry_date          VARCHAR(20),
    user_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_id_card PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (users_id, roles_id)
);

CREATE TABLE otp_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    code               INT                                     NOT NULL,
    user_id            VARCHAR(200)                            NOT NULL,
    otp_type           INT                                     NOT NULL,
    verified           BOOLEAN DEFAULT FALSE                   NOT NULL,
    expires_at         TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_otpverification PRIMARY KEY (id)
);


CREATE TABLE address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT,
    status             INT DEFAULT 1                           NOT NULL,
    house_address      VARCHAR(500),
    city               VARCHAR(500),
    state              VARCHAR(500),
    country            VARCHAR(500),
    street             VARCHAR(500),
    number             VARCHAR(5)         ,
    landmark           VARCHAR(500),
    user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE images
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT DEFAULT 0,
    status             INT DEFAULT 1                           NOT NULL,
    image_key          VARCHAR(500)                            NOT NULL,
    content_type       VARCHAR(50)                             NOT NULL,
    image_type         INT                                     NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE oauth2_registered_client
(
    id                            varchar(100)                            NOT NULL,
    client_id                     varchar(100)                            NOT NULL,
    client_id_issued_at           timestamp     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret                 varchar(200)  DEFAULT NULL,
    client_secret_expires_at      timestamp     DEFAULT NULL,
    client_name                   varchar(200)                            NOT NULL,
    client_authentication_methods varchar(1000)                           NOT NULL,
    authorization_grant_types     varchar(1000)                           NOT NULL,
    redirect_uris                 varchar(1000) DEFAULT NULL,
    post_logout_redirect_uris     varchar(1000) DEFAULT NULL,
    scopes                        varchar(1000)                           NOT NULL,
    client_settings               varchar(2000)                           NOT NULL,
    token_settings                varchar(2000)                           NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE oauth2_authorization
(
    id                            varchar(100) NOT NULL,
    registered_client_id          varchar(100) NOT NULL,
    principal_name                varchar(200) NOT NULL,
    authorization_grant_type      varchar(100) NOT NULL,
    authorized_scopes             varchar(1000) DEFAULT NULL,
    attributes                    text          DEFAULT NULL,
    state                         varchar(500)  DEFAULT NULL,
    authorization_code_value      text          DEFAULT NULL,
    authorization_code_issued_at  timestamp     DEFAULT NULL,
    authorization_code_expires_at timestamp     DEFAULT NULL,
    authorization_code_metadata   text          DEFAULT NULL,
    access_token_value            text          DEFAULT NULL,
    access_token_issued_at        timestamp     DEFAULT NULL,
    access_token_expires_at       timestamp     DEFAULT NULL,
    access_token_metadata         text          DEFAULT NULL,
    access_token_type             varchar(100)  DEFAULT NULL,
    access_token_scopes           varchar(1000) DEFAULT NULL,
    oidc_id_token_value           text          DEFAULT NULL,
    oidc_id_token_issued_at       timestamp     DEFAULT NULL,
    oidc_id_token_expires_at      timestamp     DEFAULT NULL,
    oidc_id_token_metadata        text          DEFAULT NULL,
    refresh_token_value           text          DEFAULT NULL,
    refresh_token_issued_at       timestamp     DEFAULT NULL,
    refresh_token_expires_at      timestamp     DEFAULT NULL,
    refresh_token_metadata        text          DEFAULT NULL,
    user_code_value               text          DEFAULT NULL,
    user_code_issued_at           timestamp     DEFAULT NULL,
    user_code_expires_at          timestamp     DEFAULT NULL,
    user_code_metadata            text          DEFAULT NULL,
    device_code_value             text          DEFAULT NULL,
    device_code_issued_at         timestamp     DEFAULT NULL,
    device_code_expires_at        timestamp     DEFAULT NULL,
    device_code_metadata          text          DEFAULT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE smile_id_record
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    job_id             VARCHAR(100)                            NOT NULL,
    user_id            VARCHAR(150)                            NOT NULL,
    message            VARCHAR(300),
    timestamp          VARCHAR(40)                             NOT NULL,
    job_type           INT,
    requirement_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_smile_id_record PRIMARY KEY (id)
);

CREATE TABLE investment_instruments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    name               VARCHAR(100)                            NOT NULL,
    code               VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_investment_instruments PRIMARY KEY (id)
);

CREATE TABLE investment_requirement
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    investment_id      BIGINT                                  NOT NULL,
    requirement_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_investment_requirement PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    name               VARCHAR(150)                            NOT NULL,
    code               VARCHAR(150)                            NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE country_states
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    name               VARCHAR(150)                            NOT NULL,
    country_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_country_states PRIMARY KEY (id)
);

ALTER TABLE investment_requirement
    ADD CONSTRAINT fk_investment_on_investment_instruments FOREIGN KEY (investment_id) REFERENCES investment_instruments(id);

ALTER TABLE investment_requirement
    ADD CONSTRAINT fk_investment_on_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id);

CREATE INDEX idx_investment_requirement ON investment_requirement (investment_id, requirement_id);

ALTER TABLE investment_instruments
    ADD CONSTRAINT uc_investment_type_code UNIQUE (code);

ALTER TABLE investment_instruments
    ADD CONSTRAINT uc_investment_type_name UNIQUE (name);

ALTER TABLE smile_id_record
    ADD CONSTRAINT fk_smileid_onrequirements FOREIGN KEY (requirement_id) REFERENCES requirements(id);

ALTER TABLE smile_id_record
    ADD CONSTRAINT uc_smile_id_record_job UNIQUE (job_id);

CREATE INDEX idx_smileidrecord_job_id ON smile_id_record (job_id, user_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE address
    ADD CONSTRAINT uc_address_user UNIQUE (user_id);

ALTER TABLE otp_verification
    ADD CONSTRAINT uc_otpver_code_uid_ot UNIQUE (code, user_id, otp_type);

ALTER TABLE beneficiaries
    Add CONSTRAINT uc_beneficiaries_owner_id_email UNIQUE (owner_id, email);

CREATE INDEX idx_beneficiaries_email ON beneficiaries (email);

CREATE INDEX idx_beneficiaries_owner_id ON beneficiaries (owner_id);

CREATE INDEX idx_otpver_uid_ot ON otp_verification (user_id, otp_type);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_profile
    ADD CONSTRAINT uc_user_profile_referral_code UNIQUE (referral_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_image_key_images ON images (image_key);

CREATE UNIQUE INDEX idx_onbaording_user_requirement_id ON user_onboarding(user_id, requirement_id);

CREATE INDEX idx_oauth2_registered_client_client_id ON oauth2_registered_client(client_id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_document
    ADD CONSTRAINT FK_USER_DOCUMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE UNIQUE INDEX idx_country_states_name_country_id ON country_states(name, country_id);

CREATE UNIQUE INDEX idx_countries_name_code ON countries(name, code);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES requirements (id);

ALTER TABLE user_onboarding
    ADD CONSTRAINT FK_USER_ONBOARDING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_profile
    ADD CONSTRAINT FK_USER_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permissions_id) REFERENCES permissions (id);

ALTER TABLE roles_permissions
    ADD CONSTRAINT fk_rolper_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_roles FOREIGN KEY (roles_id) REFERENCES roles (id);

CREATE INDEX idx_roles_permissions_permissions_id ON roles_permissions(permissions_id);

CREATE INDEX idx_roles_permissions_roles_id ON roles_permissions(roles_id);

CREATE INDEX idx_users_roles_user_id ON users_roles(users_id);

CREATE INDEX idx_users_roles_roles_id ON users_roles(roles_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_users FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE next_of_kin
    ADD CONSTRAINT fk_user_on_next_of_kin FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE id_card
    ADD CONSTRAINT  fk_user_on_id_card FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO requirements (
    created_date, created_by, last_modified_date, last_modified_by, version, status,
    display_name, requirement_name, mandatory
)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'BVN Verification', 'BVN', TRUE),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'Address Verification', 'PROOF_OF_ADDRESS', TRUE),
    -- IF NIN IS PROVIDED, OTHER GOVERNMENT ISSUED ID IS NOT REQUIRED
    -- (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'ID Verification', 'GOVERNMENT_ISSUED_ID', FAlSE),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 1, 1, 'ID Verification', 'NIN', TRUE);


DO $$
    DECLARE
        UsersId integer;

        RolesAdminID integer;
        RolesSuperAdminID integer;
        RolesUserID integer;

        UsersGetID integer;
        UsersUpdateStateID integer;
        UsersAssetCreateID integer;
        UsersAssetGetID integer;
        UsersPlanCreateID integer;
        UsersPlanGetID integer;
        UsersUpdateCountryID integer;
        UsersGetCountriesID integer;
        UsersGetStatesID integer;
        UsersChangePasswordID integer;
        UsersOnboardOnboardID integer;
        UsersFormsGetID integer;
        UsersBanksGetID integer;
        UsersBeneficiaryGetID integer;
        UsersBeneficiaryCreateID integer;
        UsersOnboardGetID integer;
        UsersNextOfKinCreateID integer;
        UsersNextOfKinGetID integer;
        UsersPPicturePostID integer;
        UsersSignedUrlID integer;
        UsersVirtualAccountsGetID integer;
        UsersTransactionsGetID integer;
        UsersGetSmileIdTokenID integer;
        AdminNextOfKinUpdateID integer;
        AdminChangePasswordID integer;
        UsersChangeAvatarID integer;
        UsersChangePinID integer;
        AdminChangeDobID integer;
        AdminSelectionUpdateID integer;
        AdminFormItemUpdateID integer;
        AdminChangeGenderID integer;
        UsersDeactivateAccountID integer;
        UsersGetAvatarID integer;
        UsersPhoneNumberUpdateID integer;
        SuperAdminAdminCreateID integer;
BEGIN

    -- USERS
    INSERT INTO users (created_date, created_by, last_modified_date, last_modified_by, version, email, first_name, last_name, middle_name, password, phone_number)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'oneappsuperadmin@meristemng.com', 'Super', 'Admin', '', '$2a$12$zoqPU9DmUuSysmmH47ic.OHx3tXVHf5lJDUDNtpJjC3FM5tUcVd3W', '') RETURNING id INTO UsersId;

    -- ROLES
    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'ADMIN') RETURNING id INTO RolesAdminID;

    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'SUPER_ADMIN') RETURNING id INTO RolesSuperAdminID;

    INSERT INTO roles (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'USER') RETURNING id INTO RolesUserID;

    -- PERMISSIONS
    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get') RETURNING id INTO UsersGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.state.update') RETURNING id INTO UsersUpdateStateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.country.update') RETURNING id INTO UsersUpdateCountryID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get_countries') RETURNING id INTO UsersGetStatesID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get_states') RETURNING id INTO UsersGetCountriesID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.asset.create') RETURNING id INTO UsersAssetCreateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.asset.get') RETURNING id INTO UsersAssetGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.plan.create') RETURNING id INTO UsersPlanCreateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.plan.get') RETURNING id INTO UsersPlanGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change-password') RETURNING id INTO UsersChangePasswordID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.onboard.onboard') RETURNING id INTO UsersOnboardOnboardID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.forms.get') RETURNING id INTO UsersFormsGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.banks.get') RETURNING id INTO UsersBanksGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'user.beneficiary.get') RETURNING id INTO UsersBeneficiaryGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES  (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'user.beneficiary.create') RETURNING id INTO UsersBeneficiaryCreateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.onboard.get') RETURNING id INTO UsersOnboardGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.next_of_kin.create') RETURNING id INTO UsersNextOfKinCreateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.next_of_kin.get') RETURNING id INTO UsersNextOfKinGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.p_picture.post') RETURNING id INTO UsersPPicturePostID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.generate_signed_url') RETURNING id INTO UsersSignedUrlID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.virtual_accounts.get') RETURNING id INTO UsersVirtualAccountsGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.transactions.get') RETURNING id INTO UsersTransactionsGetID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get_smile_id_token') RETURNING id INTO UsersGetSmileIdTokenID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.next_of_kin.update') RETURNING id INTO AdminNextOfKinUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.phone-number.update') RETURNING id INTO UsersPhoneNumberUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.change.password') RETURNING id INTO AdminChangePasswordID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change.images') RETURNING id INTO UsersChangeAvatarID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.change.pin') RETURNING id INTO UsersChangePinID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.change.dob') RETURNING id INTO AdminChangeDobID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.selection.update') RETURNING id INTO AdminSelectionUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.form.items.update') RETURNING id INTO AdminFormItemUpdateID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'admin.change.gender') RETURNING id INTO AdminChangeGenderID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.deactivate.account') RETURNING id INTO UsersDeactivateAccountID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'users.get.images') RETURNING id INTO UsersGetAvatarID;

    INSERT INTO permissions (created_date, created_by, last_modified_date, last_modified_by, version, status, name)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'super_admin.admin.create') RETURNING id INTO SuperAdminAdminCreateID;

    -- USERS_ROLES
    INSERT INTO users_roles VALUES (UsersId, RolesSuperAdminID);

    -- ROLES_PERMISSIONS
    INSERT INTO roles_permissions (roles_id, permissions_id)
    VALUES (RolesUserID, UsersGetID),
           (RolesUserID, UsersGetStatesID),
           (RolesUserID, UsersAssetCreateID),
           (RolesUserID, UsersAssetGetID),
           (RolesUserID, UsersPlanCreateID),
           (RolesUserID, UsersPlanGetID),
           (RolesUserID, UsersUpdateStateID),
           (RolesUserID, UsersUpdateCountryID),
           (RolesUserID, UsersGetCountriesID),
           (RolesUserID, UsersChangePasswordID),
           (RolesUserID, UsersOnboardOnboardID),
           (RolesUserID, UsersFormsGetID),
           (RolesUserID, UsersBanksGetID),
           (RolesUserID, UsersBeneficiaryGetID),
           (RolesUserID, UsersBeneficiaryCreateID),
           (RolesUserID, UsersOnboardGetID),
           (RolesUserID, UsersNextOfKinCreateID),
           (RolesUserID, UsersNextOfKinGetID),
           (RolesUserID, UsersPPicturePostID),
           (RolesUserID, UsersSignedUrlID),
           (RolesUserID, UsersVirtualAccountsGetID),
           (RolesUserID, UsersTransactionsGetID),
           (RolesUserID, UsersGetSmileIdTokenID),
           (RolesAdminID, AdminNextOfKinUpdateID),
           (RolesAdminID, AdminChangePasswordID),
           (RolesAdminID, AdminChangeDobID),
           (RolesAdminID, AdminSelectionUpdateID),
           (RolesAdminID, AdminFormItemUpdateID),
           (RolesAdminID, AdminChangeGenderID),
           (RolesUserID, UsersChangeAvatarID),
           (RolesUserID, UsersChangePinID),
           (RolesUserID, UsersDeactivateAccountID),
           (RolesUserID, UsersGetAvatarID),
           (RolesUserID, UsersPhoneNumberUpdateID),
           (RolesSuperAdminID, SuperAdminAdminCreateID);
END $$;

INSERT INTO oauth2_registered_client
VALUES
    ('b4c1e3f7-7238-4453-a68e-8a52faf61834', 'mobile-service', NOW(), '$2a$10$BayFPa39DOsXHezSVcWIrONwom81s46vDs6js4AK1fx/hRR37Rx7S', NULL, 'Mobile Service', 'client_secret_post,client_secret_basic', 'refresh_token,re_password,client_credentials', '', '', 'user.read,user.write,openid,send_otp,verify_otp,create_user,users.get,password_reset', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":false,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",57600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}'),
    ('38463a9b-55ef-4df0-a319-63f5c60475d8', 'users-service', NOW(), '$2a$10$I0HYSs94VokxDXX77ubhsudZSrz96lyfOTLetGwyTHotmJo6cX9YS', NULL, 'Users Service', 'client_secret_post,client_secret_basic', 'refresh_token,client_credentials', '', '', '', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}'),
    ('8705d10f-81b1-4095-9424-955b03e47d4a', 'notification-service', NOW(), '$2a$10$T929snsP.zmaysL7Byji1.6Y2yOvkFWniUcGl0Cb3dt3HWdXLb83a', NULL, 'Notification Service', 'client_secret_post,client_secret_basic', 'refresh_token,client_credentials', '', '', '', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');


INSERT INTO images (created_date, created_by, last_modified_date, last_modified_by, image_key, content_type, image_type)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '1.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '2.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '3.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '4.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '5.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '6.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '7.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '8.svg', 'image/svg', 1),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', '9.svg', 'image/svg', 1);

INSERT INTO investment_instruments (created_date, created_by, last_modified_date, last_modified_by, version, name, code)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Mutual Funds', 'MER-MUT-FUND'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Trusties', 'MER-TRUSTIES'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Treasury Bills', 'MER-TREAS-BILLS');

DO $$

    DECLARE
        NigeriaID integer;
BEGIN

    INSERT INTO countries(created_date, created_by, last_modified_date, last_modified_by, version, name, code)
    VALUES ( NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Nigeria', 'NG' ) RETURNING id INTO NigeriaID;

    INSERT INTO country_states(created_date, created_by, last_modified_date, last_modified_by, version, name, country_id)
    VALUES
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Abia', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Adamawa', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Akwa Ibom', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Anambra', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Bauchi', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Bayelsa', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Benue', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Borno', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Cross River', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Delta', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Ebonyi', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Edo', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Ekiti', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Enugu', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Gombe', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Imo', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Jigawa', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kaduna', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kano', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Katsina', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kebbi', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kogi', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kwara', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Lagos', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Nasarawa', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Niger', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Ogun', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Ondo', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Osun', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Oyo', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Plateau', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Rivers', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Sokoto', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Taraba', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Yobe', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Zamfara', NigeriaID),
        (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'FCT', NigeriaID);

END $$;
