CREATE TABLE vendor
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT     DEFAULT 0                       NOT NULL,
    status             INT     DEFAULT 0                       NOT NULL, -- 0 FAILED, 1 SUCCESSFUL, 2 INVALID

    vendor_code        VARCHAR(255)                            NOT NULL,
    vendor_name        VARCHAR(255)                            NOT NULL,
    is_locked          BOOLEAN DEFAULT TRUE                    NOT NULL,

    CONSTRAINT pk_vendor PRIMARY KEY (id)
);


CREATE TABLE aml_search
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL, -- 0 FAILED, 1 SUCCESSFUL, 2 INVALID

    entity_id          BIGINT                                  NOT NULL,
    client_search_id   VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_aml_search PRIMARY KEY (id),
    CONSTRAINT fk_aml_search_on_entity_id FOREIGN KEY (entity_id) REFERENCES users (id),
    CONSTRAINT uq_aml_search_client_search_id UNIQUE (client_search_id)
);

CREATE INDEX idx_aml_search_client_search_id ON aml_search (client_search_id);

CREATE TABLE aml_result
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL,

    search_id          BIGINT                                  NOT NULL,
    vendor_id          BIGINT                                  NOT NULL,

    entity_type        VARCHAR(50)                             NOT NULL, -- e.g., USER 'Person'
    entity_id          BIGINT                                  NOT NULL, -- users id

    vendor_dataset     JSONB,
    vendor_reference   VARCHAR(100),                                     -- vendor id for this request or user
    result_type        VARCHAR(20),                                      -- PEP, SANCTION, ADVERSE_MEDIA

    CONSTRAINT pk_aml_result PRIMARY KEY (id),
    CONSTRAINT fk_aml_result_on_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor (id),
    CONSTRAINT fk_aml_result_on_search_id FOREIGN KEY (search_id) REFERENCES aml_search (id),
    CONSTRAINT fk_aml_result_on_entity_id FOREIGN KEY (entity_id) REFERENCES users (id)
);

CREATE INDEX idx_aml_result_entity_id_entity_type_status ON aml_result (entity_id, entity_type, status);
CREATE INDEX idx_aml_result_entity_id_search_id_status ON aml_result (entity_id, search_id, status);


CREATE TABLE aml_decision
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INT                                              DEFAULT 0 NOT NULL,
    status             INT                                              DEFAULT 0 NOT NULL, -- 0 FAILED, 1 SUCCESSFUL, 2 INVALID

    decision_group_id  VARCHAR,                                                             -- Generated when compliance selects the relevant adverse media, pep, and sanctions details that belong to the user from the list of results
    entity_id          BIGINT                                  NOT NULL,

    decision           VARCHAR(100)                            NOT NULL,                    -- CLEARED, REJECTED, ESCALATED                                                      -- MATCH, NO_MATCH, REVIEW
    aml_type           VARCHAR(100)                            NOT NULL,                    -- CLEARED, REJECTED, ESCALATED                                                      -- MATCH, NO_MATCH, REVIEW
    decided_by         VARCHAR(100)                            NOT NULL,
    decided_date       TIMESTAMP                               NOT NULL,
    reason             TEXT                                    NOT NULL,

    CONSTRAINT pk_aml_decision PRIMARY KEY (id),
    CONSTRAINT fk_aml_decision_on_entity_id FOREIGN KEY (entity_id) REFERENCES users (id)
);

CREATE INDEX idx_aml_decision_entity_id_decision_group_id ON aml_decision (entity_id, decision_group_id);

INSERT INTO vendor(created_by, last_modified_by, vendor_name, vendor_code, is_locked)
VALUES ('SYSTEM', 'SYSTEM', 'Pastel', 'PASTEL', FALSE),
       ('SYSTEM', 'SYSTEM', 'Smile ID', 'SMILE_ID', FALSE),
       ('SYSTEM', 'SYSTEM', 'Dojah', 'DOJAH', TRUE);


