
environment: dev-env

global:
  namespace: one-meristem-app
  serviceAccountName: app-spc-sa
  create: false     # Prevent chart from trying to create it

networkpolicy:
  enabled: false


replicaCount: 2

image:
  repository: swr.af-south-1.myhuaweicloud.com/swr-repo-one-meristem-app-dev-env/users-service
  tag: latest
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

env:
  COMPANY_NAME: "Meristem Securities Limited"
  DATA_PRIVACY_POLICY_URL: "https://www.onemerristem.merristem.com"
  GREEN_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Green_Logo.png"
  WHITE_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_White_Logo.png"
  FINANCE_LOGO_URL: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Finance_Logo.png"
  SMILE_ID_PARTNER_ID: "7496"
  SMILE_ID_PROD_API_KEY: "ugXtYHgdgqYtNEkMGnKBkhTUeN4ZKx7dhN4D5rn1vAIVUh1uVmJpW1heUy6MvXOKpUxIcnVBnaVU7bZ4PrGdocNcFmuf2m9ZRQeLW2wGQosotIfZEyRLdq9wgYFlgkBeszKoG98wPGvrNLAXP9Txehvid202jfaQtH5KCz5x0FI="
  SMILE_ID_DEV_API_KEY: "3d64d61d-6d64-402d-a5f0-fa288507ec8f"
  SMILE_ID_PROD_LAMBDA_URL: "https://api.smileidentity.com/v1/"
  SMILE_ID_TEST_LAMBDA_URL: "https://testapi.smileidentity.com/v1/"
  SMILE_ID_PROD_WHITELIST_IPS: "34.240.137.52,44.230.128.108,52.36.32.43,52.213.46.74"
  SMILE_ID_DEV_WHITELIST_IPS: "35.166.227.53,44.246.19.66,54.246.37.255,99.81.237.141"
  SMILE_ID_DEV_CALLBACK_URL: "https://www.onemerristem.merristem.com/api/users/onboard/smile-id/webhook"
  APP_PROFILE: "dev"
  GITHUB_BRANCH: "dev_env"
  USER: "System"
  ONE_APP_SERVER_URL: "https://" #placeholder for the EIP IP
  ONE_APP_EMAIL: "hello@onemeristem.meristemng.com"
  CONSUL_HOST: "consul"
  USERS_SERVICE_HOSTNAME: users-service
  USERS_SERVICE_URI: "http://users-service:20020"
  CONFIG_SERVER_URI: "http://config-server:20000/config"
  HUAWEI_OBS_ENDPOINT: "obs.af-south-1.myhuaweicloud.com"
  HUAWEI_OBS_IMAGES_BUCKET: "obs-image-storage-one-meristem-dev-env"
  HUAWEI_OBS_DOC_BUCKET: "obs-documents-one-meristem-dev-env"
  OKHI_DEV_AND_PROD_WHITELIST_IP: "52.18.220.93,18.202.96.242"
  ADMIN_USERNAME: "admin"  # Replace with your actual admin username
  TRUSTEES_CLIENT_ID: trustees-service
  MOBILE_SECRET: secret
  TRUSTEES_SECRET: secret
  NOTIFICATION_SECRET: secret
  HUAWEI_OBS_UNSTRUCTURED_BUCKET: "obs-unstructured-logo-one-meristem-dev-env"
  GEOIP_DB_LOCATION: "/app/data/geoip/GeoLite2-City.mmdb"
  MERISTEM_GREEN_LOGO: "https://obs-unstructured-logo-one-meristem-dev-env.obs.af-south-1.myhuaweicloud.com/Meristem_Green_Logo.png"
  SUPPORT_PHONE: "0700-MERISTEM"
  SUPPORT_EMAIL: "support@onemeristem.com"

secretEnv:
  ADMIN_PASSWORD:
    secretName: credentials
    secretKey: key3
  DB_SERVER:
    secretName: huawei-csms-credentials
    secretKey: DB_SERVER
  USERS_DB_NAME:
    secretName: huawei-csms-credentials
    secretKey: USERS_DB_NAME
  USERS_DB_USERNAME:
    secretName: huawei-csms-credentials
    secretKey: USERS_DB_USERNAME
  USERS_DB_PASSWORD:
    secretName: huawei-csms-credentials
    secretKey: USERS_DB_PASSWORD
  KAFKA_HOST_URL:
    secretName: huawei-csms-credentials
    secretKey: KAFKA_HOST_URL
  REDIS_HOST:
    secretName: huawei-csms-credentials
    secretKey: REDIS_HOST
  REDIS_PASSWORD:
    secretName: huawei-csms-credentials
    secretKey: REDIS_PASSWORD
  MAILER_HOST:
    secretName: credentials
    secretKey: key5
  MAILER_USERNAME:
    secretName: credentials
    secretKey: key6
  MAILER_PASSWORD:
    secretName: credentials
    secretKey: key7
  HUAWEI_ACCESS_KEY_ID:
    secretName: credentials
    secretKey: key11
  HUAWEI_SECRET_ACCESS_KEY_ID:
    secretName: credentials
    secretKey: key12
  H2_PASSWORD:
    secretName: credentials
    secretKey: key13
  TRUSTEES_CLIENT_SECRET: 
    secretName: credentials
    secretKey: key16

volumeMounts:
  - name: huawei-csms-credentials
    mountPath: /mnt/secrets-store/users-service
    readOnly: true
  - name: users-data
    mountPath: /mnt/users
  - name: secret-volume
    mountPath: /etc/secrets-store/users-service
    readOnly: true
  - name: users-service-storage
    mountPath: /app/data/geoip 
    readOnly: true

volumes:
  - name: users-data
    emptyDir: {}
  - name: huawei-csms-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: huawei-csms-credentials
        #csi.storage.k8s.io/provisioner-secret-name: huawei-csms-credentials
        #csi.storage.k8s.io/provisioner-secret-namespace: one-meristem-app
  - name: secret-volume
    secret:
      secretName: credentials
  - name: users-service-storage
    persistentVolumeClaim:
      claimName: users-service-pvc


resources:
  limits:
    cpu: "0.7"
    memory: 720Mi
  requests:
    cpu: "0.5"
    memory: 512Mi

imagePullSecrets:
  - name: huawei-swr-auth #relying on CCE's automatic injection

# pvc:
#   name: users-service-pvc-evs
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: csi-disk-topology
#   volumeMode: Filesystem

# Persistent Volume configuration
pv:
  name: pv-obs-users-service

pvc:
  name: users-service-pvc
  size: 500Mi




# HorizontalPodAutoscaler configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70


# service configuration
service:
  type: ClusterIP
  name: users-service
  port: 8082
  targetPort: 20020
