
spring:
  application:
    name: gateway-service
  config:
    import: configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      label: dev
      profile: local
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}


logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
