# Middleware Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${MIDDLEWARE_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH} 
    path: ${HELM_REPO_PATH}/${MIDDLEWARE_SERVICE_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${MIDDLEWARE_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true