#------------------ ARGO CD APPLICATIONS ------------------#
# This file contains the Argo CD applications configuration for deploying the one-meristem-app microservices.


# Shared Resources Application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-resources
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH} 
    path: ${HELM_REPO_PATH}/shared-resources
    helm:
      valueFiles:
        - ${VALUES_FILE}
      parameters:  # The secret for OBS auth for Users-service.
        - name: obsSecret.data.accessKey
          value: "SFBVQUVaSzNETExQTFZGWFpJQzU="
        - name: obsSecret.data.secretKey
          value: "c05weTlSN0FjN0JIZU9VcDVhRGhyRERkY1lFYWh1M1BVQnNWM0s0NQ=="
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:  # For Cross-Namespace Access.
      labels:
        argocd.argoproj.io/managed-by: shared-resources
  # Allow resources in other namespaces
  # Allow resources in other namespaces
  ignoreDifferences: 
    - group: ""
      kind: Secret
      name: huawei-credentials-obs-ak
      namespace: one-meristem-app
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels

---

# Config Server Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${CONFIG_SERVER_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH}
    path: ${HELM_MOBILE_REPO_PATH}/${CONFIG_SERVER_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Consul Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${CONSUL_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH} 
    path: ${HELM_MOBILE_REPO_PATH}/${CONSUL_APP_NAME}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
---
# Notification Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NOTIFICATION_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH}
    path: ${HELM_MOBILE_REPO_PATH}/${NOTIFICATION_SERVICE_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Wallet Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${WALLET_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH} 
    path: ${HELM_MOBILE_REPO_PATH}/${WALLET_SERVICE_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Report Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${REPORT_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH} 
    path: ${HELM_MOBILE_REPO_PATH}/${REPORT_SERVICE_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Users Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${USERS_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH}
    path: ${HELM_MOBILE_REPO_PATH}/${USERS_SERVICE_APP_NAME}
    helm:
      valueFiles: 
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Trustees Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${TRUSTEES_SERVICE_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH}
    path: ${HELM_MOBILE_REPO_PATH}/${TRUSTEES_SERVICE_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# Cloud Gateway Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${CLOUD_GATEWAY_APP_NAME}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: ${ARGOCD_PROJECT}
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${GIT_BRANCH}
    path: ${HELM_MOBILE_REPO_PATH}/${CLOUD_GATEWAY_APP_NAME}
    helm:
      valueFiles:
        - ${VALUES_FILE}
  destination:
    server: ${CLUSTER_SERVER_URL}
    namespace: ${APP_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

