# # Middleware Service Application
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: 
#   namespace: argocd
# spec:
#   project: one-meristem-app
#   source:
#     repoURL: 
#     targetRevision: stag_env 
#     path: charts/
#     helm:
#       valueFiles:
#         - values-stag_env.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: 
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
