#------------------ ARGO CD APPLICATIONS ------------------#
# This file contains the Argo CD applications configuration for deploying the one-meristem-app microservices.


# Shared Resources Application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-resources
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env 
    path: charts/shared-resources
    helm:
      valueFiles:
        - values.yaml
      parameters:  # The secret for OBS auth for Users-service.
        - name: obsSecret.data.accessKey
          value: "SFBVQUVaSzNETExQTFZGWFpJQzU="
        - name: obsSecret.data.secretKey
          value: "c05weTlSN0FjN0JIZU9VcDVhRGhyRERkY1lFYWh1M1BVQnNWM0s0NQ=="
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:  # For Cross-Namespace Access.
      labels:
        argocd.argoproj.io/managed-by: shared-resources
  # Allow resources in other namespaces
  # Allow resources in other namespaces
  ignoreDifferences: 
    - group: ""
      kind: Secret
      name: obs-access-secret
      namespace: one-meristem-app
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels

---

# Config Server Application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env
    path: charts/mobile-backend/config-server
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Consul Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env 
    path: charts/mobile-backend/consul
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
---
# Notification Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env
    path: charts/mobile-backend/notification-service
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Wallet Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallet-service
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env 
    path: charts/mobile-backend/wallet-service
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Report Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: report-service
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env 
    path: charts/mobile-backend/report-service
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Users Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-service
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env
    path: charts/mobile-backend/users-service
    helm:
      valueFiles: 
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# Trustees Service Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trustees-service
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env
    path: charts/mobile-backend/trustees-service
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# Cloud Gateway Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-gateway
  namespace: argocd
spec:
  project: one-meristem-app-stag
  source:
    repoURL: https://github.com/mit-meristem/one_meristem_app.git
    targetRevision: stag_env
    path: charts/mobile-backend/cloud-gateway
    helm:
      valueFiles:
        - values-stag_env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: one-meristem-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

