# #------------------- ARGOCD CUSTOM SETUP -------------------#
# # This file contains argo custom setup configurations for deploying argo.

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd-custom-setup
#   namespace: ${ARGOCD_NAMESPACE}
# spec:
#   project: ${ARGOCD_PROJECT}
#   source:
#     repoURL: ${GIT_REPO_URL}
#     targetRevision: ${GIT_BRANCH}
#     path: /applications/bootstrap
#   destination:
#     server: ${CLUSTER_SERVER_URL}
#     namespace: ${ARGOCD_NAMESPACE}
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true