
CREATE TABLE wallets
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                        TIMESTAMP                               NOT NULL,
    created_by                          VARCHAR(255)                            NOT NULL,
    last_modified_date                  TIMESTAMP,
    last_modified_by                    VARCHAR(255)                            NOT NULL,
    version                             INTEGER,
    status                              INTEGER DEFAULT 1                       NOT NULL,
    full_name                           VARCHAR(200)                            NOT NULL,
    user_id                             BIGINT                                  NOT NULL,
    balance                             DECIMAL(14, 4) DEFAULT 0.0              NOT NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id)
);


CREATE TABLE virtual_accounts
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                        TIMESTAMP                               NOT NULL,
    created_by                          VARCHAR(255)                            NOT NULL,
    last_modified_date                  TIMESTAMP,
    last_modified_by                    VARCHAR(255)                            NOT NULL,
    version                             INTEGER,
    status                              INTEGER DEFAULT 1                       NOT NULL,
    bank_code                           VARCHAR(20)                             NOT NULL,
    account_number                      VARCHAR(20)                             NOT NULL,
    account_name                        VARCHAR(200)                            NOT NULL,
    provider                            VARCHAR(20)                             NOT NULL,
    balance                             DECIMAL(14, 4)                          NOT NULL,
    wallet_id                           BIGINT                                  NOT NULL,
    CONSTRAINT "pk_virtual-account" PRIMARY KEY (id)
);


CREATE TABLE transactions (
                              id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              created_date       TIMESTAMP                               NOT NULL,
                              created_by         VARCHAR(255)                            NOT NULL,
                              last_modified_date TIMESTAMP,
                              last_modified_by   VARCHAR(255)                            NOT NULL,
                              version            INTEGER,
                              status             INTEGER DEFAULT 1                       NOT NULL,
                              wallet_id          BIGINT                                  NOT NULL,
                              virtual_account_id BIGINT,
                              reference          VARCHAR(50)                             NOT NULL,
                              amount             DECIMAL(14,4)                           NOT NULL,
                              previous_balance   DECIMAL(14,4)                           NOT NULL,
                              new_balance        DECIMAL(14,4)                           NOT NULL,
                              type               INTEGER                                 NOT NULL,
                              method             INTEGER                                 NOT NULL,
                              narration          VARCHAR(255),
                              metadata JSON,
                              provider_reference       VARCHAR(50)                    NOT NULL,
                              senders_bank_name          VARCHAR(100),
                              senders_name          VARCHAR(100),
                              senders_bank_code          VARCHAR(20),
                              senders_account_number          VARCHAR(20),

                              CONSTRAINT "pk_transactions" PRIMARY KEY (id)
);


CREATE SEQUENCE wema_virtual_account_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1;


ALTER TABLE virtual_accounts
    ADD CONSTRAINT FK_VIRTUAL_ACCOUNTS_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallets (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallets(id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_VIRTUAL_ACCOUNT FOREIGN KEY (virtual_account_id) REFERENCES virtual_accounts (id);

CREATE UNIQUE INDEX IDX_VIRTUAL_ACCOUNT_WALLET_ID_BANK_CODE ON virtual_accounts(wallet_id, bank_code);

CREATE UNIQUE INDEX IDX_TRANSACTIONS_REFERENCE ON transactions(reference);

CREATE UNIQUE INDEX IDX_WALLET_USER_ID ON wallets(user_id);
