apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wallet-service.fullname" . }}-pdb
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "wallet-service.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "wallet-service.selectorLabels" . | nindent 6 }}
