# apiVersion: v1
# kind: Service
# metadata:
#   name: wallet-service
#   namespace: one-meristem-app
#   labels:
#     app: wallet-service
# spec:
#   type: ClusterIP
#   ports:
#     - name: wallet-service
#       port: 20040
#       protocol: TCP
#       targetPort: 20040
#   selector:
#     app: wallet-service


apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "wallet-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "wallet-service.name" . }}