# ingress.yaml (Sharing the same ingress with the argo cd as they use same elb)
# external-ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace | default .Release.Namespace }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "cce" }}
  tls:
{{- if .Values.ingress.tls.enabled }}
    - secretName: {{ .Values.ingress.tls.secretName | default "" | quote }}
{{- end }}
  rules:
{{- range .Values.ingress.rules }}
    - host: {{ .host | default "" | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "consul.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
{{- end }}
