# apiVersion: v1
# kind: Service
# metadata: 
#   name: consul
#   namespace: one-meristem-app
#   annotations:
#     service
#   labels:
#     app: consul
# spec:
#   type: NodePort
#   selector:
#     app: consul
#   ports:
#     - name: consul
#       port: 8500
#       protocol: TCP
#       targetPort: 8500
#       nodePort: 30000
#   #To get the IP = "http://<Node-IP>:<NodePort>"


apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "consul.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "consul.name" . }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
