# Build environment
FROM maven:3.9.8-eclipse-temurin-21-alpine AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn -B -f./pom.xml package -DskipTests

# Production packaging
FROM openjdk:21-jdk
LABEL maintainer="Kingsley Godwin <kingsleygodwin@meristemng.com>"

WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/cloud-gateway*.jar /app/cloud-gateway.jar
EXPOSE 20011 
ENTRYPOINT ["java", "-Dspring.lifecycle.timeout-per-shutdown-phase=10s", "-jar", "cloud-gateway.jar",]
