# #Persistent Volume (PV)
pv:
  name: pv-obs-users-service
  size: 500Mi
  volumeHandle: obs-microservice-storage-one-meristem-app-stag-env # <-- Replace with actual OBS bucket name
  enterpriseProjectID: ad2cb210-4c6e-47dd-9a5a-bcc02dc3faeb # <-- Replace with actual Enterprise Project ID
  region: af-south-1
  obsVolumeType: STANDARD
  secretName: huawei-credentials-obs-ak

#Roles
namespace: one-meristem-app
role:
  name: sa-secret-role

#Role Binding
roleBinding:
  name: sa-secret-rolebinding

#Secrets
k8sSecret:
  name: credentials

#SecretProviderClass
environment: stag-env
secretProviderClass:
  name: huawei-csms-credentials
  provider: cce
  k8sSecretName: huawei-csms-credentials

serviceAccount:
  name: app-spc-sa
  dewResources:
    - "db-admin-secret-one-meristem-app-dev-env"
    - "redis-middleware-credentials-one-meristem-app-dev-env"
    - "redis-mobile-backend-credentials-one-meristem-app-dev-env"
    - "kafka-credentials-one-meristem-app-dev-env"
    - "db-notification_service-secret-one-meristem-app-dev-env"
    - "db-users_service-secret-one-meristem-app-dev-env"
    - "db-wallet_service-secret-one-meristem-app-dev-env"
    - "db-report_service-secret-one-meristem-app-dev-env"
    - "db-trustees_service-secret-one-meristem-app-dev-env"

# image pull secret
imagePullSecret:
  dockerconfigjson: "eyJhdXRocyI6eyJzd3IuYWYtc291dGgtMS5teWh1YXdlaWNsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImFmLXNvdXRoLTFASFBVQUVaSzNETExQTFZGWFpJQzUiLCJwYXNzd29yZCI6ImJiZTFhYzgxZjBkNjRjZDczYWM0MmFhOWEzYmZlODBiY2MzNGE4MmM1M2VkMmMwNWQ4MGU5NTQ5NDM5NzlkZWIiLCJlbWFpbCI6InRhbGsybHVnYXJkQGdtYWlsLmNvbSIsImF1dGgiOiJZV1l0YzI5MWRHZ3RNVUJJVUZWQlJWcExNMFJNVEZCTVZrWllXa2xETlRvM05UVTVNVFU1TkRVNE9UVXpPRFF3In19fQ==%"
obsSecret:
  enabled: true
  name: huawei-credentials-obs-ak
  namespace: one-meristem-app
  # data:
  #   accessKey: "MDAwMDAwMDEwMDAwMDAwMTc3ODY4MjBBMkM2RjBFNzBGQzQ3QTE5RjgxNTY2NzBFNzY2NjIxOEY1NTMyRUM5MjU3RTU1QUE1MTY4QkNFODU3NEEyOEJGRDM2OUIzNTU3RTVCRkE5NTQ0Mzk3NEZENg=="
  #   secretKey: "MDAwMDAwMDEwMDAwMDAwMTc3MEQ4NDMzQjU2OTZFQjA4MUNFRjE4OTA3NTkzNUFGOEMyMUMzNzhBMjEzMjU0QzQ1NkYxQzc0NjMwQkY1OTBEOUIxRDZFRDlBNjRGMTdFNjU2QUVFODFBODExRTYwRDE0Nzk0QjAxQzIwRURDMDQ2NDkxOUYyOUEzRDYzMDAy"
