namespace: one-meristem-app

serviceAccount:
  name: app-spc-sa-prod
  dewResources:
    - "db-admin-secret-one-meristem-app-prod-env"
    - "redis-middleware-credentials-one-meristem-app-prod-env"
    - "redis-mobile-backend-credentials-one-meristem-app-prod-env"
    - "kafka-credentials-one-meristem-app-prod-env"
    - "db-notification_service-secret-one-meristem-app-prod-env"
    - "db-users_service-secret-one-meristem-app-prod-env"
    - "db-wallet_service-secret-one-meristem-app-prod-env"
    - "db-report_service-secret-one-meristem-app-prod-env"
    - "db-trustees_service-secret-one-meristem-app-prod-env"
