spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          timeout: 4
          skip-ssl-validation: true
          search-paths:
            - backend/meriapp-config
          clone-on-start: true
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: ${GITHUB_BRANCH}
          try-master-branch: false
        encrypt:
          enabled: true
      fail-fast: true
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

server:
  port: 20000
  servlet:
    context-path: /config

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    refresh:
      access: read_only

logging:
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  # TODO: delete when going live
#  level:
#    org.springframework.web: debug
#    org.springframework.cloud: debug

encrypt:
  key: '${ENCRYPTION_KEY}'