#!/bin/bash
set -e

# Default values if not passed via environment
USERS_DB_NAME=${DB_NAME_USERS_SERVICE:-"users-service"}
NOTIFICATION_DB_NAME=${DB_NAME_NOTIFICATION_SERVICE:-"notification-service"}
WALLET_DB_NAME=${DB_NAME_WALLET_SERVICE:-"wallet-service"}
REPORT_DB_NAME=${DB_NAME_REPORT_SERVICE:-"report-service"}
CORE_DB_NAME=${DB_NAME_CORE_SERVICE:-"core-service"}

USERS_DB_USER=${USERS_DB_USERNAME:-"users-service"}
USERS_DB_PASS=${USERS_DB_PASSWORD:-admin-657-A1}

NOTIFICATION_DB_USER=${NOTIFICATION_DB_USERNAME:-"notification-service"}
NOTIFICATION_DB_PASS=${NOTIFICATION_DB_PASSWORD:-admin-657-A1}

WALLET_DB_USER=${WALLET_DB_USERNAME:-"wallet-service"}
WALLET_DB_PASS=${WALLET_DB_PASSWORD:-admin-657-A1}

REPORT_DB_USER=${REPORT_DB_USERNAME:-"report-service"}
REPORT_DB_PASS=${REPORT_DB_PASSWORD:-admin-657-A1}

CORE_DB_USER=${CORE_DB_USERNAME:-"core-service"}
CORE_DB_PASS=${CORE_DB_PASSWORD:-admin-657-A1}

echo "Creating databases and assigning users..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$USERS_DB_NAME";
  CREATE DATABASE "$NOTIFICATION_DB_NAME";
  CREATE DATABASE "$WALLET_DB_NAME";
  CREATE DATABASE "$REPORT_DB_NAME";
  CREATE DATABASE "$CORE_DB_NAME";

  CREATE USER "$USERS_DB_USER" WITH PASSWORD '$USERS_DB_PASS';
  CREATE USER "$NOTIFICATION_DB_USER" WITH PASSWORD '$NOTIFICATION_DB_PASS';
  CREATE USER "$WALLET_DB_USER" WITH PASSWORD '$WALLET_DB_PASS';
  CREATE USER "$REPORT_DB_USER" WITH PASSWORD '$REPORT_DB_PASS';
  CREATE USER "$CORE_DB_USER" WITH PASSWORD '$CORE_DB_PASS';

  GRANT ALL PRIVILEGES ON DATABASE "$USERS_DB_NAME" TO "$USERS_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$NOTIFICATION_DB_NAME" TO "$NOTIFICATION_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$WALLET_DB_NAME" TO "$WALLET_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$REPORT_DB_NAME" TO "$REPORT_DB_USER"
  GRANT ALL PRIVILEGES ON DATABASE "$WALLET_DB_NAME" TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$NOTIFICATION_DB_NAME" TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$USERS_DB_NAME" TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$REPORT_DB_NAME" TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$CORE_DB_NAME" TO "$CORE_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$CORE_DB_NAME" TO "$POSTGRES_USER";
  

EOSQL

echo "Databases and users successfully set up."
