#!/bin/bash
set -e

POSTGRES_USER="${POSTGRES_USER:-admin}"

# =============================
# Users Service
# =============================
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "${DB_NAME_USERS_SERVICE}";
    CREATE USER "${DB_USERS_USERNAME}" WITH PASSWORD '${DB_USERS_PASSWORD}';
    GRANT CONNECT ON DATABASE "${DB_NAME_USERS_SERVICE}" TO "${DB_USERS_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME_USERS_SERVICE}" TO "${DB_USERS_USERNAME}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${DB_NAME_USERS_SERVICE}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "${DB_USERS_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DB_USERS_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DB_USERS_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DB_USERS_USERNAME}";
EOSQL


# =============================
# Notification Service
# =============================
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "${DB_NAME_NOTIFICATION_SERVICE}";
    CREATE USER "${DB_NOTIFICATION_USERNAME}" WITH PASSWORD '${DB_NOTIFICATION_PASSWORD}';
    GRANT CONNECT ON DATABASE "${DB_NAME_NOTIFICATION_SERVICE}" TO "${DB_NOTIFICATION_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME_NOTIFICATION_SERVICE}" TO "${DB_NOTIFICATION_USERNAME}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${DB_NAME_NOTIFICATION_SERVICE}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "${DB_NOTIFICATION_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DB_NOTIFICATION_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DB_NOTIFICATION_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DB_NOTIFICATION_USERNAME}";
EOSQL


# =============================
# Wallet Service
# =============================
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "${DB_NAME_WALLET_SERVICE}";
    CREATE USER "${DB_WALLET_USERNAME}" WITH PASSWORD '${DB_WALLET_PASSWORD}';
    GRANT CONNECT ON DATABASE "${DB_NAME_WALLET_SERVICE}" TO "${DB_WALLET_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME_WALLET_SERVICE}" TO "${DB_WALLET_USERNAME}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${DB_NAME_WALLET_SERVICE}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "${DB_WALLET_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DB_WALLET_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DB_WALLET_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DB_WALLET_USERNAME}";
EOSQL


# =============================
# Report Service
# =============================
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "${DB_NAME_REPORT_SERVICE}";
    CREATE USER "${DB_REPORT_USERNAME}" WITH PASSWORD '${DB_REPORT_PASSWORD}';
    GRANT CONNECT ON DATABASE "${DB_NAME_REPORT_SERVICE}" TO "${DB_REPORT_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME_REPORT_SERVICE}" TO "${DB_REPORT_USERNAME}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${DB_NAME_REPORT_SERVICE}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "${DB_REPORT_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DB_REPORT_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DB_REPORT_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DB_REPORT_USERNAME}";
EOSQL


# =============================
# Trusties Service
# =============================
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "${DB_NAME_TRUSTIES_SERVICE}";
    CREATE USER "${DB_TRUSTIES_USERNAME}" WITH PASSWORD '${DB_TRUSTIES_PASSWORD}';
    GRANT CONNECT ON DATABASE "${DB_NAME_TRUSTIES_SERVICE}" TO "${DB_TRUSTIES_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME_TRUSTIES_SERVICE}" TO "${DB_TRUSTIES_USERNAME}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${DB_NAME_TRUSTIES_SERVICE}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "${DB_TRUSTIES_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DB_TRUSTIES_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DB_TRUSTIES_USERNAME}";
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DB_TRUSTIES_USERNAME}";
EOSQL


echo "All databases, users, and privileges configured successfully."
