CREATE TABLE forms
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP                               NOT NULL,
    created_by          VARCHAR(255)                            NOT NULL,
    last_modified_date  TIMESTAMP,
    last_modified_by    VARCHAR(255)                            NOT NULL,
    version             INTEGER,
    status              INTEGER DEFAULT 1                       NOT NULL,
    form_position       INTEGER                                 NOT NULL,
    label               VARCHAR(255)                            NOT NULL,
    placeholder         VARCHAR(255),
    subtext             VARCHAR(255),
    type                VARCHAR(100)                            NOT NULL,
    field_order         INT                                     NOT NULL,
    mandatory           INT                                     NOT NULL,
    text_size           INT,
    default_value       VARCHAR(300),
    form_version        VARCHAR(5)        DEFAULT 'v1'                      NOT NULL,
    CONSTRAINT pk_forms PRIMARY KEY (id)
);



CREATE TABLE selections
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    form_id            BIGINT                                  NOT NULL,
    selection_value    VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_selections PRIMARY KEY (id)
);

CREATE TABLE banks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    status             INTEGER DEFAULT 1                       NOT NULL,
    name               VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_banks PRIMARY KEY (id)
);

ALTER TABLE selections
    ADD CONSTRAINT FK_SELECTIONS_ON_FORM FOREIGN KEY (form_id) REFERENCES forms (id);


CREATE TABLE currencies
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP                               NOT NULL,
    created_by          VARCHAR(255)                            NOT NULL,
    last_modified_date  TIMESTAMP,
    last_modified_by    VARCHAR(255)                            NOT NULL,
    version             INTEGER,
    status              INTEGER DEFAULT 1                       NOT NULL,
    currency_name VARCHAR(255)                            NOT NULL,
    currency_logo VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

CREATE INDEX IDX_FORMS_FORM_POSITION ON forms (form_position);



-- INTEGER("INTEGER"),
--     STRING("STRING"),
--     MONEY("MONEY"),
--     NUMBER("NUMBER"),
--     PHONE_NUMBER("PHONE_NUMBER"),
--     EMAIL("EMAIL"),
--     FILE("FILE"),
--     DATE("DATE"),
--     SELECTION("SELECTION");

--
-- CASH("Cash", 1),
-- PUBLIC_EQUITIES("Public Equities", 2),
-- PRIVATE_EQUITIES("Private Equities", 3),
-- FINTECH_WALLET("Fintech Wallets", 4),
-- REAL_ESTATE("Real Estate", 5),
-- FIXED_INCOME_MONEY_MARKET("Fixed Income/Money Market", 6),
-- INTELLECTUAL_PROPERTY("Intellectual Property", 7),
-- ALTERNATE_ASSETS("Alternate Assets", 8),
-- CRYPTOCURRENCY_AND_NFT("Cryptocurrencies & NFT", 9),
-- DIGITAL_PLATFORM("Digital Platform", 10),
-- PERSONAL_ASSETS("Personal Assets", 11),
-- PENSION("Pension", 12),
-- LIFE_INSURANCE("Life Insurance", 13);

INSERT INTO currencies (created_date, created_by, last_modified_date, last_modified_by, version, currency_name, currency_logo)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'NGN', 'logo_url'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'USD', 'logo_url'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'EUR', 'logo_url'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'CAD', 'logo_url'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'GBP', 'logo_url'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'AED', 'logo_url');


-------------------------**************************************-----------------------------------------------

INSERT INTO banks (created_date, created_by, last_modified_date, last_modified_by, version, name)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Access Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Accion Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Citibank Nigeria Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Coronation Merchant Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Covenant Microfinance Bank Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Ecobank Nigeria'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Empire Trust Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Fidelity Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Fina Trust Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Finca Microfinance Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'First Bank of Nigeria Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'First City Monument Bank Limited(FCMB)'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Globus Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Guaranty Trust Holding Company Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Heritage Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Infinity Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Jaiz Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Keystone Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Kuda Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'LOTUS BANK'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Mint Finex MFB'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Mkobo MFB'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Moniepoint Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Mutual Trust Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Nova Merchant Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Opay'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Palmpay'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Parallex Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Sparkle Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Peace Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Pearl Microfinance Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Polaris Bank Limited. The successor to Skye Bank Plc.'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'PremiumTrust Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Providus Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Rand Merchant Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Rephidim Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Rubies Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Shepherd Trust Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Stanbic IBTC Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Standard Chartered'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Sterling Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'SunTrust Bank Nigeria Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'TAJBank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Titan Trust Bank Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Union Bank of Nigeria Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'United Bank for Africa Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Unity Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'VFD Microfinance Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Wema Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'Zenith Bank Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 'OTHERS');


-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, form_version)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'Account Name', 'Enter Account Name', 'STRING', 1, 1, 255, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'Account Number', 'Enter Account Number', 'STRING', 2, 1, 255, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'Account Type', 'Select Account Type', 'SELECTION', 3, 1, 255, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 4, 1, null,'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 1, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 5,
        0, 300, 'v1');


SET
@CashAccountTypeID = (SELECT id FROM forms WHERE form_position = 1 AND field_order = 3);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @CashAccountTypeID, 'Savings'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @CashAccountTypeID, 'Current');

INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Company Type', null, 'STRING', 1, 1, null, 'Public', 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Asset Category', null, 'SELECTION', 2, 1, null, 'Public Equities',
        'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Brokerage House', 'Choose Brokerage House', 'SELECTION', 3, 1, null,
        null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'CSCS Number', 'Enter CSCS Number', 'STRING', 4, 1, 255, null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'CHN', 'Enter CHN', 'STRING', 5, 1, 255, null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Number of Units', 'Enter Number of Units owned', 'NUMBER', 6, 1, null,
        null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 7, 1, null, null,
        'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 2, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 8,
        0, 300, null, 'v1');


-------------------------**************************************-----------------------------------------------


SET
@PublicEquitiesAssetCategoryID = (SELECT id FROM forms WHERE form_position = 2 AND field_order = 2);
SET
@PublicEquitiesBrokerageHouseID = (SELECT id FROM forms WHERE form_position = 2 AND field_order = 3);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesAssetCategoryID, 'Public'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesAssetCategoryID, 'Others');

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Absa Securities Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Afrinvest Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Anchoria Investment and Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Apel Asset Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'APT Securities & Funds Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'ARM Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Arthur Stevens Asset Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Associated Asset Managers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Atlass Portfolio Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Ava Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Bauchi Investment Corporation Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Belfry Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Bestworth Assets & Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Calyx Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Camry Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Capital Assets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Capital Bancorp Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Capital Express Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Capital Trust Brokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'CardinalStone Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Cashville Investments & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'CDL Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Centre Point Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Century Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Chapel Hill Denham Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Chartwell Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Citi Investment Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'City Code Trust & Invest Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Compass Investments & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Cordros Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Core Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Coronation Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Cowry Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Crossworld Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Crown Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'CSL Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Deep Trust & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'De-Lords Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'DLM Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Dominion Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'DSU Brokerage Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Dunbell Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Dynamic Portfolio Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'EDC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Edgefield Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'EFG Hermes Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'El-Elyon Alliance and Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Enterprise Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Equity Capital Solutions Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Eurocomm Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Express Portfolio Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Falcon Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FBC Trust & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FBNQuest Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FCSL Asset Management Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Fidelity Finance Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Financial & Analytics Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Financial Trust Company Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Finmal Finance Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'First Integrated Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FIS Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Foresight Securities & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Forte Financial Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Forthright Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Fortress Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FSDH Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'FSL Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Funds Matrix & Asset Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Fundvine Capital & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Futureview Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Gem Assets Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Gidauniya Invest & Sec Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Global Asset Management (Nig) Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Globalview Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Golden Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Marimpex Finance & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Maxifund Investment & Securities Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'MBC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Mega Equities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Meristem Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Midas Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Midpoint Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Milestone Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Mission Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'ML Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Molten Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Morgan Capital Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Mountain Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Mutual Alliance Invest & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Network Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Networth Securities & Finance Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Newdevco Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Nigerian Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Norrenberger Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Nova Finance & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'NOVAMBL Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Osborne Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'PAC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Parthian Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Peace Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Pilot Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Pinefields Investment Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'PIPC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Pivot Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Planet Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Portfolio Advisers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Premium Capital and Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Prominent Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'PSL Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Pyramid Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Qualinvest Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Quantum Zenith Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Rainbow Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Readings Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Regency Assets Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Rencap Securities (Nig) Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Resort Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Reward Investment & Service Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'RMB Nigeria Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Rostrum Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Rowet Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Royal Crest Finance Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Royal Guaranty & Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Sankore Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Santrust Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Securities & Capital Management Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Securities Africa Financial Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Security Swaps Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Shalom Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Shelong Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Sigma Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Signet Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Skyview Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Smadac Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Solid Rock Securities & Investment Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Spring Board Trust & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Spring Trust & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Stanbic IBTC Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Standard Alliance Capital & Asset Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Standard Union Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'StoneX Financial Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'The Bridge Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Tiddo Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Tomil Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Topmost Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Tower Securities & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Trade link Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Traders Trust & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Transworld Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Trust Yields Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Trustbanc Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Trusthouse Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'TRW Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Tyndale Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'UCML Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'UIDC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'UNEX Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'United Capital Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Valmon Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Valueline Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Vetiva Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'WCM Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'WSTC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Zion Stockbrokers & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PublicEquitiesBrokerageHouseID, 'Others');


-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Company Type', null, 'STRING', 1, 1, null, 'Private', 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Brokerage House', 'Choose Brokerage House', 'SELECTION', 2, 1, null,
        null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Shares of Listed Company', 'Select Shares of Listed Company',
        'SELECTION', 3, 1, 255, null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Number of Units', 'Enter Number of Units owned', 'NUMBER', 6, 1, null,
        null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 7, 1, null, null,
        'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 3, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 8,
        0, 300, null, 'v1');

SET
@PrivateEquitiesBrokerageHouseID = (SELECT id FROM forms WHERE form_position = 3 AND field_order = 2);
SET
@PrivateEquitiesSharesofListedCompanyID = (SELECT id FROM forms WHERE form_position = 3 AND field_order = 3);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Absa Securities Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Afrinvest Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Anchoria Investment and Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Apel Asset Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'APT Securities & Funds Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'ARM Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Arthur Stevens Asset Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Associated Asset Managers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Atlass Portfolio Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Ava Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Bauchi Investment Corporation Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Belfry Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Bestworth Assets & Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Calyx Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Camry Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Capital Assets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Capital Bancorp Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Capital Express Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Capital Trust Brokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'CardinalStone Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Cashville Investments & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'CDL Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Centre Point Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Century Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Chapel Hill Denham Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Chartwell Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Citi Investment Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'City Code Trust & Invest Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Compass Investments & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Cordros Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Core Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Coronation Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Cowry Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Crossworld Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Crown Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'CSL Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Deep Trust & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'De-Lords Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'DLM Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Dominion Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'DSU Brokerage Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Dunbell Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Dynamic Portfolio Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'EDC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Edgefield Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'EFG Hermes Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'El-Elyon Alliance and Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Enterprise Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Equity Capital Solutions Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Eurocomm Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Express Portfolio Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Falcon Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FBC Trust & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FBNQuest Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FCSL Asset Management Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Fidelity Finance Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Financial & Analytics Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Financial Trust Company Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Finmal Finance Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'First Integrated Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FIS Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Foresight Securities & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Forte Financial Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Forthright Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Fortress Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FSDH Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'FSL Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Funds Matrix & Asset Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Fundvine Capital & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Futureview Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Gem Assets Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Gidauniya Invest & Sec Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Global Asset Management (Nig) Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Globalview Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Golden Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Marimpex Finance & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Maxifund Investment & Securities Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'MBC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Mega Equities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Meristem Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Midas Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Midpoint Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Milestone Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Mission Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'ML Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Molten Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Morgan Capital Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Mountain Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Mutual Alliance Invest & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Network Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Networth Securities & Finance Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Newdevco Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Nigerian Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Norrenberger Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Nova Finance & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'NOVAMBL Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Osborne Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'PAC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Parthian Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Peace Capital Markets Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Pilot Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Pinefields Investment Services Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'PIPC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Pivot Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Planet Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Portfolio Advisers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Premium Capital and Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Prominent Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'PSL Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Pyramid Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Qualinvest Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Quantum Zenith Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Rainbow Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Readings Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Regency Assets Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Rencap Securities (Nig) Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Resort Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Reward Investment & Service Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'RMB Nigeria Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Rostrum Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Rowet Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Royal Crest Finance Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Royal Guaranty & Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Sankore Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Santrust Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Securities & Capital Management Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Securities Africa Financial Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Security Swaps Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Shalom Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Shelong Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Sigma Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Signet Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Skyview Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Smadac Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Solid Rock Securities & Investment Plc'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Spring Board Trust & Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Spring Trust & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Stanbic IBTC Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Standard Alliance Capital & Asset Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Standard Union Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'StoneX Financial Nigeria Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'The Bridge Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Tiddo Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Tomil Trust Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Topmost Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Tower Securities & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Trade link Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Traders Trust & Investment Company Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Transworld Investment & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Trust Yields Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Trustbanc Capital Management Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Trusthouse Investment Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'TRW Stockbrokers Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Tyndale Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'UCML Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'UIDC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'UNEX Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'United Capital Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Valmon Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Valueline Securities & Investments Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Vetiva Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'WCM Capital Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'WSTC Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Zion Stockbrokers & Securities Limited'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesBrokerageHouseID, 'Others');


INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ABBEY MORTGAGE BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ACADEMY PRESS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ACCESS HOLDINGS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AFRICA PRUDENTIAL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AFRICAN ALLIANCE INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AFROMEDIA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AIICO INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AIRTEL AFRICA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ALUMINIUM EXTRUSION IND. PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ARBICO PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ARDOVA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ASO SAVINGS AND LOANS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ASSOCIATED BUS COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AUSTIN LAZ & COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'AXAMANSARD INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'BERGER PAINTS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'BETA GLASS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'BRICLINKS AFRICA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'BUA CEMENT PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'BUA FOODS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'C & I LEASING PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CADBURY NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CAP PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CAPITAL HOTEL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CAPITAL OIL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CAVERTON OFFSHORE SUPPORT GRP PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CHAMPION BREW. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CHAMS HOLDING COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CHELLARAMS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CONOIL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CONSOLIDATED HALLMARK INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CORNERSTONE INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CORONATION INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'COURTEVILLE BUSINESS SOLUTIONS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CUSTODIAN INVESTMENT PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CUTIX PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'CWG PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'DAAR COMMUNICATIONS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'DANGOTE CEMENT PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'DANGOTE SUGAR REFINERY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'DEAP CAPITAL MANAGEMENT & TRUST PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'DN TYRE & RUBBER PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'E-TRANZACT INTERNATIONAL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ECOBANK TRANSNATIONAL INCORPORATED'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'EKOCORP PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ELLAH LAKES PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ETERNA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'EUNISELL INTERLINKED PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FBN HOLDINGS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FCMB GROUP PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FIDELITY BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FIDSON HEALTHCARE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FLOUR MILLS NIG. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'FTN COCOA PROCESSORS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GEREGU POWER PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GLAXO SMITHKLINE CONSUMER NIG. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GLOBAL SPECTRUM ENERGY SERVICES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GOLDEN GUINEA BREW. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GOLDLINK INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GREIF NIGERIA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GUARANTY TRUST HOLDING COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GUINEA INSURANCE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'GUINNESS NIG PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'HONEYWELL FLOUR MILL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'IKEJA HOTEL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'INDUSTRIAL & MEDICAL GASES NIGERIA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'INFINITY TRUST MORTGAGE BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'INTERNATIONAL BREWERIES PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'INTERNATIONAL ENERGY INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'JAIZ BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'JAPAUL GOLD & VENTURES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'JOHN HOLT PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'JULI PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'JULIUS BERGER NIG. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LAFARGE AFRICA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LASACO ASSURANCE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LEARN AFRICA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LINKAGE ASSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LIVESTOCK FEEDS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'LIVINGTRUST MORTGAGE BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MAY & BAKER NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MCNICHOLS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MEDVIEW AIRLINE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MEYER PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MORISON INDUSTRIES PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MRS OIL NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MTN NIGERIA COMMUNICATIONS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MULTI-TREX INTEGRATED FOODS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MULTIVERSE MINING AND EXPLORATION PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'MUTUAL BENEFITS ASSURANCE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'N NIG. FLOUR MILLS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NASCON ALLIED INDUSTRIES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NCR (NIGERIA) PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NEIMETH INTERNATIONAL PHARMACEUTICALS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NEM INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NESTLE NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGER INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGERIA ENERYGY SECTOR FUND'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGERIAN AVIATION HANDLING COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGERIAN BREW. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGERIAN ENAMELWARE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NIGERIAN EXCHANGE GROUP'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NOTORE CHEMICAL IND PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'NPF MICROFINANCE BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'OANDO PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'OKOMU OIL PALM PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'OMATEK VENTURES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'PZ CUSSONS NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'PHARMA-DEKO PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'PREMIER PAINTS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'PRESCO PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'PRESTIGE ASSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'R T BRISCOE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'RAK UNITY PET. COMP. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'RED STAR EXPRESS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'REGENCY ASSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'RESORT SAVINGS & LOANS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'RONCHESS GLOBAL RESOURCES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ROYAL EXCHANGE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'S C O A NIG. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SECURE ELECTRONIC TECHNOLOGY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SEPLAT ENERGY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SFS REAL ESTATE INVESTMENT TRUST'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SKYWAY AVIATION HANDLING COMPANY PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SMART PRODUCTS NIGERIA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SOVEREIGN TRUST INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'STACO INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'STANBIC IBTC HOLDINGS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'STANDARD ALLIANCE INSURANCE PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'STERLING BANK PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'SUNU ASSURANCES NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TANTALIZERS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'THE INITIATES PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'THOMAS WYATT NIG. PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TOTALENERGIES MARKETING NIGERIA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TOURIST COMPANY OF NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TRANS-NATIONWIDE EXPRESS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TRANSCORP HOTELS PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TRANSNATIONAL CORPORATION PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'TRIPPLE GEE AND COMPANY PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'U A C N PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UH REAL ESTATE INVESTMENT TRUST'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNILEVER NIGERIA PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNION BANK NIG.PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNION DICON SALT PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNION HOMES SAVINGS AND LOANS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNITED BANK FOR AFRICA PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNITED CAPITAL PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNITY BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNIVERSAL INSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UNIVERSITY PRESS PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UPDC PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'UPDC REAL ESTATE INVESTMENT TRUST'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'VERITAS KAPITAL ASSURANCE PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'VITAFOAM NIG PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'WEMA BANK PLC.'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'ZENITH BANK PLC'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PrivateEquitiesSharesofListedCompanyID, 'Others');


-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, form_version)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 4, 'Fintech App', 'Choose Fintech App', 'SELECTION', 1, 1, null, 'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 4, 'Email/Unique ID', 'Enter app email/unique id', 'STRING', 2, 1, 320,
        'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 4, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 3, 1, null,
        'v1'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 4, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 4,
        0, 300, 'v1');

SET
@FintechWalletsFintechAppID = (SELECT id FROM forms WHERE form_position = 4 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'PiggyVest'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Cowrywise'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Osusu'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Grey'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Cardify'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'CardRemit'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Risevest'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Bamboo'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Chaka'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Trove'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Paystack'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Flutterwave'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Remita'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Moniepoint'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Opay'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'PalmPay'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Kuda Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'FairMoney'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Carbon'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Renmoney'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Branch'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Aella Credit'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'QuickCheck'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Lendigo'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Lidya'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Migo'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Fairscore'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FintechWalletsFintechAppID, 'Other');



-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Property Type', 'Select Property Type', 'SELECTION', 1, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Property Description', 'Land size, duplex, number of rooms, etc',
        'STRING', 2, 1, 255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Property Address', 'Enter street, city, state and country', 'STRING',
        3, 1, 255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Property Document', 'No File Chosen', 'MONEY', 7, 1, null,
        'Choose File', 'v1', 'Only supports .jpg, .png and .pdf'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 7, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 5, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 8,
        0, 300, null, 'v1', null);


SET @RealEstatePropertyTypeID = (SELECT id FROM forms WHERE form_position = 5 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @RealEstatePropertyTypeID, 'Commercial'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @RealEstatePropertyTypeID, 'Residential'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @RealEstatePropertyTypeID, 'Personal Home'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @RealEstatePropertyTypeID, 'Land');

-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 6, 'Asset Type', 'Select Asset Type', 'SELECTION', 1, 1, null, null, 'v1',
        null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 6, 'Investment House', 'Select Investment House', 'SELECTION', 2, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 6, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 3, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 6, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 4,
        0, 300, null, 'v1', null);


SET @FixedIncomeAssetTypeID = (SELECT id FROM forms WHERE form_position = 6 AND field_order = 1);
SET @FixedIncomeInvestmentHouseID = (SELECT id FROM forms WHERE form_position = 6 AND field_order = 2);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Mutual Funds'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Commercial Papers'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Bonds'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Treasury Bills'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Funds Deposit'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Fixed Deposit'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeAssetTypeID, 'Others');

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Meristem Wealth Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Aiico Capital'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Afrinvest Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Alpha Morgan Capital'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'APEL Asset Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'ARM'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Arthur Stevens Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Asset Management Corporation Of Nigeria'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Atlantic Global Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Bulls Capital Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Cash Craft Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'CDL Asset Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Capital field Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'CitiTrust Investment'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Coronation Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Covenant Securities & Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Cowry Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Edgefield Capital Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Emerging Africa Capital Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'FBN Quest Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'FCSL Asset Management Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Forte Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'FSDH'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Forthright Securities and Investment Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'FRAGG Investment Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Frontier Capital Alternative Assets Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Funds Matrix & Assets Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'GDL Nigeria'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'GFX Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Investment One Financial Services'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Investment Shark Asset Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Lead Capital Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Light House Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Lotus Capital Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Marathon Asset and Fund Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Maven Asset Management Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Mega Capital Financial Services Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'N.I.D Project & Asset Managers'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Norrenberger'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'PAC Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Pac Investment company'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Peninsula Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Planet Capital Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Radix Capital Partners Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Rand Merchant Bank'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Reebak Investment Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Stanbic IBTC Asset Management'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Sterling Asset Management & Trustees'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Tower Asset Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'United Capital'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'ValuAlliance Asset Management Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Venerate Capital'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'VFD Group'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'Zenith Capital'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @FixedIncomeInvestmentHouseID, 'OTHERS');


-------------------------**************************************-----------------------------------------------



INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 7, 'Property Type', 'Select Property Type', 'SELECTION', 1, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 7, 'Registered Name', 'Enter Registered property name', 'STRING', 2, 1,
        255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 7, 'Property Description', 'Briefly describe Intellectual Property',
        'STRING', 3, 1, 255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 7, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 4, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 7, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 5,
        0, 300, null, 'v1', null);


SET @IntellectualPropertyPropertyType = (SELECT id FROM forms WHERE form_position = 7 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @IntellectualPropertyPropertyType, 'Copyright'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @IntellectualPropertyPropertyType, 'Patent'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @IntellectualPropertyPropertyType, 'Trademark'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @IntellectualPropertyPropertyType, 'Design');


-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 8, 'Asset Type', 'Select Asset Type', 'SELECTION', 1, 1, null, null, 'v1',
        null);

SET @AlternateAssetsAssetType = (SELECT id FROM forms WHERE form_position = 8 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @AlternateAssetsAssetType, 'Cryptocurrencies & NFT'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @AlternateAssetsAssetType, 'Digital Platform');

-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Asset Type', null, 'SELECTION', 1, 1, null, 'Cryptocurrencies & NFT',
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Wallet Address', 'Enter Valid Wallet Address', 'STRING', 2, 1, 300,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Platform', 'Enter Asset Platform', 'STRING', 3, 1, 255, null, 'v1',
        null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Registered Email/Unique ID', 'Enter Registered Email or Unique ID',
        'STRING', 4, 1, 320, null, 'v1', 'Only supports .jpg, .png and .pdf'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 7, 1, null, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 9, 'Other Details (Optional)', 'Enter Additional Information', 'STRING', 8,
        0, 300, null, 'v1', null);

SET @CryptoNFTAssetType = (SELECT id FROM forms WHERE form_position = 9 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @CryptoNFTAssetType, 'Cryptocurrencies & NFT'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @CryptoNFTAssetType, 'Digital Platform');

-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 10, 'Asset Type', null, 'SELECTION', 1, 1, null, 'Digital Platform', 'v1',
        null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 10, 'Platform', 'Enter Asset Platform', 'STRING', 3, 1, 255, null, 'v1',
        null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 10, 'Registered Email/Unique ID', 'Enter Registered Email or Unique ID',
        'STRING', 4, 1, 320, null, 'v1', 'Only supports .jpg, .png and .pdf'),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 10, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 7, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 10, 'Other Details (Optional)', 'Enter Additional Information', 'STRING',
        8, 0, 300, null, 'v1', null);


SET @DigitalPlatformAssetType = (SELECT id FROM forms WHERE form_position = 10 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @DigitalPlatformAssetType, 'Cryptocurrencies & NFT'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @DigitalPlatformAssetType, 'Digital Platform');

-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 11, 'Asset Type', 'Select Asset Type', 'SELECTION', 1, 1, null, null, 'v1',
        null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 11, 'Asset Description', 'Briefly describe Personal Asset', 'STRING', 2, 1,
        255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 11, 'Identifying Number', 'e.g. Car Plate Number', 'STRING', 3, 1, 255,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 11, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 4, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 11, 'Other Details (Optional)', 'Enter Additional Information', 'STRING',
        5, 0, 300, null, 'v1', null);


SET @PersonalAssetTypeID = (SELECT id FROM forms WHERE form_position = 11 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PersonalAssetTypeID, 'Artwork'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PersonalAssetTypeID, 'Automobile'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PersonalAssetTypeID, 'Jewelry'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PersonalAssetTypeID, 'Antiques'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PersonalAssetTypeID, 'Others');

-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 12, 'PFA (PENSION FUND ADMINISTRATOR)',
        'Select PFA (PENSION FUND ADMINISTRATOR)', 'SELECTION', 1, 1, null, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 12, 'RSA (RETIRED SAVINGS ACCOUNT)', 'Enter RSA Number', 'STRING', 2, 1,
        255, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 12, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 4, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 12, 'Other Details (Optional)', 'Enter Additional Information', 'STRING',
        5, 0, 300, null, 'v1', null);

SET @PFAID = (SELECT id FROM forms WHERE form_position = 12 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'ARM Pension Managers'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Crusader Sterling Pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'FCMB Pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Fidelity Pension Managers'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'First Guarantee Pension Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Guarantee Trust pension managers limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'IEI-Anchor pension managers limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Leadway Pensure PFA Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Nigerian University Pension management company'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'NLPC Pension fund administrators limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'NPF Pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Oak Pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Pensions Alliance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Premium Pension Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Radix Pension Manager Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Sigma Pensions Limited '),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Stanbic IBTC pension Managers Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Tangerine APT pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Trustfunds Pensions Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Veritas Glanvills Pensions limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @PFAID, 'Others');
-------------------------**************************************-----------------------------------------------


INSERT INTO forms (created_date, created_by, last_modified_date, last_modified_by, version, form_position, label,
                   placeholder, type, field_order, mandatory, text_size, default_value, form_version, subtext)
VALUES (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 13, 'Insurance Company', 'Select Insurance Company', 'SELECTION', 1, 1,
        null, null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 13, 'Policy Number', 'Enter Policy Number', 'STRING', 2, 1, 255, null,
        'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 13, 'Expiry Date', 'Select Insurance Expiry Date', 'DATE', 3, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 13, 'Estimated Amount', 'Enter Estimated Amount', 'MONEY', 4, 1, null,
        null, 'v1', null),
       (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, 13, 'Other Details (Optional)', 'Enter Additional Information', 'STRING',
        5, 0, 300, null, 'v1', null);


SET @LifeInsuranceCompanyID = (SELECT id FROM forms WHERE form_position = 13 AND field_order = 1);

INSERT INTO selections (created_date, created_by, last_modified_date, last_modified_by, version, form_id, selection_value)
VALUES
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'African Alliance Insurance Company Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'AIICO Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Alliance & General Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'ALLIANZ NIGERIA INSURANCE PLC'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Anchor Insurance Company Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'ARM Life Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'AXA Mansard Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Capital Express Assurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Consolidated Hallmark Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Continental Reinsurance Company Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Cornerstone Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Custodian & Allied Insurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Custodian Life Assurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'FBN General Insurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'FBN Insurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Fin Insurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Great Nigeria Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Guinea Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Goldlink Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'International Energy Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Industrial & General Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'JAIZ TAKAFUL INSURANCE PLC'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'KBL Insurance Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'LASACO Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Law Union & Rock Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Leadway Assurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Linkage Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Tangerine Life Insurance Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Mutual Benefits Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Mutual Benefits Life Assurance Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'NEM Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'NICON Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Niger Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Nigeria Reinsurance Corporation'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Nigerian Agricultural Insurance Corporation'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'NSIA Insurance Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Old Mutual Nigeria General Insurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Old Mutual Nigeria Life Assurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Prestige Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Prudential Zenith Life Assurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Regency Alliance Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Royal Exchange Prudential Life'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Royal Exchange Prudential Life'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Unitrust Insurance Nigeria Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Sovereign Trust Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'STACO Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Standard Alliance Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Sterling Assurance Nigeria Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'SUNU Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'UNIC Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Universal Insurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Veritas Kapital Assurance Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Coronation Insurance'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Coronation Life Assurance Ltd'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'Zenith General Insurance Company Limited'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'GOXI Micro insurance'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'NOOR Takaful Plc'),
    (NOW(), 'SYSTEM', NOW(), 'SYSTEM', 0, @LifeInsuranceCompanyID, 'OTHERS');
