/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgotPassword` | `/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/passwordResetSuccess` | `/passwordResetSuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/resetPassword` | `/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/setupPassword` | `/setupPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifyForgotPasswordOtp` | `/verifyForgotPasswordOtp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifyOtp` | `/verifyOtp`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgotPassword` | `/forgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/passwordResetSuccess` | `/passwordResetSuccess`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/resetPassword` | `/resetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/setupPassword` | `/setupPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verifyForgotPasswordOtp` | `/verifyForgotPasswordOtp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verifyOtp` | `/verifyOtp`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/createAccount${`?${string}` | `#${string}` | ''}` | `/createAccount${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgotPassword${`?${string}` | `#${string}` | ''}` | `/forgotPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/passwordResetSuccess${`?${string}` | `#${string}` | ''}` | `/passwordResetSuccess${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/resetPassword${`?${string}` | `#${string}` | ''}` | `/resetPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/setupPassword${`?${string}` | `#${string}` | ''}` | `/setupPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verifyForgotPasswordOtp${`?${string}` | `#${string}` | ''}` | `/verifyForgotPasswordOtp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verifyOtp${`?${string}` | `#${string}` | ''}` | `/verifyOtp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgotPassword` | `/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/passwordResetSuccess` | `/passwordResetSuccess`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/resetPassword` | `/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/setupPassword` | `/setupPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifyForgotPasswordOtp` | `/verifyForgotPasswordOtp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verifyOtp` | `/verifyOtp`; params?: Router.UnknownInputParams; };
    }
  }
}
